// ایمپورت توابع مورد نیاز از Firebase
import { collection, addDoc } from "firebase/firestore";

import { initializeApp } from "firebase/app";
import { getFirestore } from "firebase/firestore";

const firebaseConfig = {
  apiKey: "AIzaSyDBPoIsElQfbMGbWRfJwtHaHxN2fYS6Czo",
  authDomain: "moji-kala.firebaseapp.com",
  projectId: "moji-kala",
  storageBucket: "moji-kala.firebasestorage.app",
  messagingSenderId: "360981434010",
  appId: "1:360981434010:web:55fc4cae46e15ffc99d923",
  measurementId: "G-9E1V0157ZE",
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

// فرض کنید فایل firebase.js که تنظیمات مربوط به Firebase رو داره در همین پوشه قرار داره
export const laptop = [
  {
    id: 1,
    name: "MacBook Pro 16-inch",
    category: "laptop",
    price: 2399,
    colors: ["Silver", "Black"],
    description:
      "Professional laptop with Apple M2 Pro chip, Liquid Retina XDR display, and 21-hour battery life.",
    brand: "Apple",
    images: [
      "/images/laptops/MacBook Pro 16-inch.jpg",
      "/images/laptops/MacBook Pro 16-inch-2.jpg",
      "/images/laptops/MacBook Pro 16-inch-3.jpg",
    ],
    stock: 80,
    rating: 4.9,
    specs: {
      cpu: "Apple M2 Pro (12-core)",
      gpu: "38-core GPU",
      ram: "32GB",
      storage: "1TB SSD",
      display: "16.2-inch Liquid Retina XDR (3456x2234)",
      os: "macOS Ventura",
      battery: "100Wh",
      weight: "2.1 kg",
    },
    features: ["Touch ID", "6-speaker system", "Thunderbolt 4 ports"],
    reviews: [
      {
        user: "Eve White",
        rating: 5,
        comment: "The ultimate machine for creative work!",
      },
    ],
  },
  {
    id: 2,
    name: "Dell XPS 13",
    category: "laptop",
    price: 1499,
    colors: ["Silver", "Black", "white"],
    description:
      "Ultra-slim laptop with Intel i7-1250U, 16GB RAM, and 13.4-inch InfinityEdge display.",
    brand: "Dell",
    images: [
      "/images/laptops/Dell XPS 13.jpg",
      "/images/laptops/Dell XPS 13-2.jpg",
      "/images/laptops/Dell XPS 13-3.jpg",
      "/images/laptops/Dell XPS 13-4.jpg",
    ],
    stock: 100,
    rating: 4.6,
    specs: {
      cpu: "Intel Core i7-1250U",
      gpu: "Intel Iris Xe",
      ram: "16GB",
      storage: "512GB SSD",
      display: "13.4-inch FHD+ (1920x1200)",
      os: "Windows 11 Pro",
      battery: "60Wh",
      weight: "1.17 kg",
    },
    features: ["Backlit keyboard", "Wi-Fi 6E", "Fingerprint reader"],
    reviews: [
      {
        user: "David Lee",
        rating: 5,
        comment: "Perfect balance of portability and power.",
      },
    ],
  },
  {
    id: 3,
    name: "HP Spectre x360",
    category: "laptop",
    price: 1799,
    colors: ["Silver", "Black", "white"],
    description:
      "2-in-1 convertible laptop with 4K OLED touchscreen and 11th Gen Intel i7.",
    brand: "HP",
    images: [
      "/images/laptops/HP Spectre x360.jpg",
      "/images/laptops/HP Spectre x360-2.jpg",
      "/images/laptops/HP Spectre x360-3.jpg",
      "/images/laptops/HP Spectre x360-4.jpg",
      "/images/laptops/HP Spectre x360-5.jpg",
    ],
    stock: 70,
    rating: 4.8,
    specs: {
      cpu: "Intel Core i7-1195G7",
      gpu: "Intel Iris Xe",
      ram: "16GB",
      storage: "1TB SSD",
      display: "13.5-inch 4K OLED (3840x2400)",
      os: "Windows 11 Home",
      battery: "66Wh",
      weight: "1.3 kg",
    },
    features: ["360° hinge", "Stylus support", "Bang & Olufsen audio"],
    reviews: [],
  },
  {
    id: 4,
    name: "Lenovo ThinkPad X1 Carbon",
    category: "laptop",
    price: 1499,
    colors: ["Silver", "Black", "white"],
    description:
      "Business laptop with MIL-STD durability, 14-inch 4K display, and LTE connectivity.",
    brand: "Lenovo",
    images: [
      "/images/laptops/Lenovo ThinkPad X1 Carbon.jpg",
      "/images/laptops/Lenovo ThinkPad X1 Carbon-2.jpg",
      "/images/laptops/Lenovo ThinkPad X1 Carbon-3.jpg",
      "/images/laptops/Lenovo ThinkPad X1 Carbon-4.jpg",
    ],
    stock: 50,
    rating: 4.7,
    specs: {
      cpu: "Intel Core i7-1165G7",
      gpu: "Intel Iris Xe",
      ram: "16GB",
      storage: "512GB SSD",
      display: "14-inch 4K (3840x2400)",
      os: "Windows 11 Pro",
      battery: "57Wh",
      weight: "1.13 kg",
    },
    features: ["TrackPoint", "Dolby Atmos", "4G LTE"],
    reviews: [],
  },
  {
    id: 5,
    name: "Asus ROG Zephyrus G14",
    category: "laptop",
    price: 1799,
    colors: ["Silver", "Black", "white"],
    description:
      "Gaming laptop with AMD Ryzen 9 6900HS, RTX 3060, and 14-inch 120Hz display.",
    brand: "Asus",
    images: [
      "/images/laptops/Asus ROG Zephyrus G14.jpg",
      "/images/laptops/Asus ROG Zephyrus G14-2.jpg",
      "/images/laptops/Asus ROG Zephyrus G14-3.jpg",
      "/images/laptops/Asus ROG Zephyrus G14-4.jpg",
    ],
    stock: 60,
    rating: 4.9,
    specs: {
      cpu: "AMD Ryzen 9 6900HS",
      gpu: "NVIDIA RTX 3060 (6GB)",
      ram: "32GB",
      storage: "1TB SSD",
      display: "14-inch QHD (2560x1440) 120Hz",
      os: "Windows 11 Home",
      battery: "76Wh",
      weight: "1.7 kg",
    },
    features: ["AniMe Matrix LED", "RGB keyboard", "Hi-Res audio"],
    reviews: [],
  },
  {
    id: 6,
    name: "Microsoft Surface Laptop 4",
    category: "laptop",
    price: 1299,
    colors: ["Silver", "Black", "white"],
    description:
      "Sleek laptop with PixelSense touchscreen, AMD Ryzen 5, and Alcantara keyboard deck.",
    brand: "Microsoft",
    images: [
      "/images/laptops/Microsoft Surface Laptop 4.jpg",
      "/images/laptops/Microsoft Surface Laptop 4-2.jpg",
      "/images/laptops/Microsoft Surface Laptop Studio-3.jpg",
      "/images/laptops/Microsoft Surface Laptop Studio-4.jpg",
      "/images/laptops/Microsoft Surface Laptop Studio-5.jpg",
    ],
    stock: 80,
    rating: 4.6,
    specs: {
      cpu: "AMD Ryzen 5 4680U",
      gpu: "AMD Radeon Graphics",
      ram: "8GB",
      storage: "256GB SSD",
      display: "13.5-inch PixelSense (2256x1504)",
      os: "Windows 11 Home",
      battery: "47.4Wh",
      weight: "1.27 kg",
    },
    features: ["Alcantara finish", "Studio Mics", "Windows Hello"],
    reviews: [],
  },
  {
    id: 7,
    name: "Acer Predator Helios 300",
    category: "laptop",
    price: 1599,
    colors: ["Silver", "Black", "white"],
    description:
      "Gaming laptop with Intel i7-12700H, RTX 3070 Ti, and 15.6-inch 144Hz display.",
    brand: "Acer",
    images: [
      "/images/laptops/Acer Predator Helios 300.jpg",
      "/images/laptops/Acer Predator Helios 300-2.jpg",
      "/images/laptops/Acer Predator Helios 300-3.jpg",
      "/images/laptops/Acer Predator Helios 300-4.jpg",
      "/images/laptops/Acer Predator Helios 300-5.jpg",
    ],
    stock: 90,
    rating: 4.8,
    specs: {
      cpu: "Intel Core i7-12700H",
      gpu: "NVIDIA RTX 3070 Ti (8GB)",
      ram: "16GB",
      storage: "1TB SSD",
      display: "15.6-inch FHD (1920x1080) 144Hz",
      os: "Windows 11 Home",
      battery: "90Wh",
      weight: "2.3 kg",
    },
    features: ["RGB keyboard", "CoolBoost technology", "Wi-Fi 6"],
    reviews: [],
  },
  {
    id: 8,
    name: "Razer Blade 15",
    category: "laptop",
    price: 1899,
    colors: ["Silver", "Black", "white"],
    description:
      "Premium gaming laptop with Intel i7-12800H, RTX 3070 Ti, and CNC aluminum chassis.",
    brand: "Razer",
    images: [
      "/images/laptops/Razer Blade 15.jpg",
      "/images/laptops/Razer Blade 15-2.jpg",
      "/images/laptops/Razer Blade 15-3.jpg",
      "/images/laptops/Razer Blade 15-4.jpg",
      "/images/laptops/Razer Blade 15-5.jpg",
    ],
    stock: 50,
    rating: 4.7,
    specs: {
      cpu: "Intel Core i7-12800H",
      gpu: "NVIDIA RTX 3070 Ti (8GB)",
      ram: "16GB",
      storage: "1TB SSD",
      display: "15.6-inch QHD (2560x1440) 240Hz",
      os: "Windows 11 Home",
      battery: "80Wh",
      weight: "2.01 kg",
    },
    features: ["Per-key RGB", "Vapor Chamber cooling", "THX Spatial Audio"],
    reviews: [],
  },
  {
    id: 9,
    name: "Samsung Galaxy Book Pro",
    category: "laptop",
    price: 1299,
    colors: ["Silver", "Black", "white"],
    description:
      "Ultra-light laptop with AMOLED display, Intel i7-1260P, and 5G connectivity.",
    brand: "Samsung",
    images: [
      "/images/laptops/Samsung Galaxy Book Pro.jpg",
      "/images/laptops/Samsung Galaxy Book Pro-2.jpg",
      "/images/laptops/Samsung Galaxy Book Pro-3.jpg",
      "/images/laptops/Samsung Galaxy Book Pro-4.jpg",
      "/images/laptops/Samsung Galaxy Book Pro-5.jpg",
    ],
    stock: 75,
    rating: 4.5,
    specs: {
      cpu: "Intel Core i7-1260P",
      gpu: "Intel Iris Xe",
      ram: "16GB",
      storage: "512GB SSD",
      display: "15.6-inch AMOLED (1920x1080)",
      os: "Windows 11 Home",
      battery: "63Wh",
      weight: "1.05 kg",
    },
    features: ["5G support", "S Pen compatibility", "AKG speakers"],
    reviews: [],
  },
  {
    id: 10,
    name: "Google Pixelbook Go",
    category: "laptop",
    price: 799,
    colors: ["Silver", "Black", "white"],
    description:
      "Lightweight Chromebook with 13.3-inch Full HD display, Intel i5, and 12-hour battery.",
    brand: "Google",
    images: [
      "/images/laptops/Google Pixelbook Go.jpg",
      "/images/laptops/Google Pixelbook Go-2.jpg",
      "/images/laptops/Google Pixelbook Go-3.jpg",
      "/images/laptops/Google Pixelbook Go-4.jpg",
      "/images/laptops/Google Pixelbook Go-5.jpg",
      "/images/laptops/Google Pixelbook Go-6.jpg",
    ],
    stock: 90,
    rating: 4.4,
    specs: {
      cpu: "Intel Core i5-10210U",
      gpu: "Intel UHD Graphics",
      ram: "8GB",
      storage: "128GB SSD",
      display: "13.3-inch FHD (1920x1080)",
      os: "Chrome OS",
      battery: "47Wh",
      weight: "1.09 kg",
    },
    features: ["Titan C security", "Backlit keyboard", "Hush Keys"],
    reviews: [],
  },

  {
    id: 11,
    name: "MSI Stealth 15M",
    category: "laptop",
    price: 1699,
    colors: ["Silver", "Black", "white"],
    description:
      "Ultra-thin gaming laptop with RTX 3060, 144Hz display, and advanced cooling system.",
    images: [
      "/images/laptops/MSI Stealth 15M.jpg",
      "/images/laptops/MSI Stealth 15M-2.jpg",
      "/images/laptops/MSI Stealth 15M-3.jpg",
      "/images/laptops/MSI Stealth 15M-4.jpg",
      "/images/laptops/MSI Stealth 15M-5.jpg",
    ],
    brand: "MSI",
    stock: 45,
    rating: 4.7,
    specs: {
      cpu: "Intel Core i7-1185G7",
      gpu: "NVIDIA RTX 3060 (6GB)",
      ram: "16GB",
      storage: "1TB SSD",
      display: "15.6-inch FHD (1920x1080) 144Hz",
      os: "Windows 11 Home",
      battery: "82Wh",
      weight: "1.7kg",
    },
    features: ["Per-Key RGB Keyboard", "Thunderbolt 4", "Hi-Res Audio"],
    reviews: [],
  },
  {
    id: 12,
    name: "LG Gram 17",
    category: "laptop",
    price: 1799,
    colors: ["Silver", "Black", "white"],
    description:
      "Lightweight 17-inch laptop with military-grade durability and 19.5-hour battery life.",
    images: [
      "/images/laptops/LG Gram 17.jpg",
      "/images/laptops/LG Gram 17-2.jpg",
      "/images/laptops/LG Gram 17-3.jpg",
      "/images/laptops/LG Gram 17-4.jpg",
    ],
    brand: "LG",
    stock: 30,
    rating: 4.8,
    specs: {
      cpu: "Intel Core i7-1260P",
      gpu: "Intel Iris Xe",
      ram: "16GB",
      storage: "1TB SSD",
      display: "17-inch WQXGA (2560x1600)",
      os: "Windows 11 Home",
      battery: "80Wh",
      weight: "1.35kg",
    },
    features: [
      "DCI-P3 99% Color Gamut",
      "Fingerprint Reader",
      "Backlit Keyboard",
    ],
    reviews: [],
  },
  {
    id: 13,
    name: "Acer Swift X",
    category: "laptop",
    price: 1299,
    colors: ["Silver", "Black", "white"],
    description:
      "Creator-focused laptop with AMD Ryzen 7 5825U and RTX 3050 Ti for content creation.",
    images: [
      "/images/laptops/Acer Swift X.jpg",
      "/images/laptops/Acer Swift X-2.jpg",
      "/images/laptops/Acer Swift X-3.jpg",
    ],
    brand: "Acer",
    stock: 55,
    rating: 4.6,
    specs: {
      cpu: "AMD Ryzen 7 5825U",
      gpu: "NVIDIA RTX 3050 Ti (4GB)",
      ram: "16GB",
      storage: "512GB SSD",
      display: "14-inch FHD IPS (1920x1080)",
      os: "Windows 11 Home",
      battery: "59Wh",
      weight: "1.39kg",
    },
    features: ["Wi-Fi 6", "USB4 Support", "Blue Light Shield"],
    reviews: [],
  },
  {
    id: 14,
    name: "Huawei MateBook X Pro",
    category: "laptop",
    price: 1499,
    colors: ["Silver", "Black", "white"],
    description:
      "Sleek 3K touchscreen laptop with aluminum unibody design and 11th Gen Intel processor.",
    images: [
      "/images/laptops/Huawei MateBook X Pro.webp",
      "/images/laptops/Huawei MateBook X Pro-2.jpg",
      "/images/laptops/Huawei MateBook X Pro-3.jpg",
      "/images/laptops/Huawei MateBook X Pro-4.jpg",
      "/images/laptops/Huawei MateBook X Pro-5.jpg",
      "/images/laptops/Huawei MateBook X Pro-6.jpg",
    ],
    brand: "Huawei",
    stock: 40,
    rating: 4.7,
    specs: {
      cpu: "Intel Core i7-1195G7",
      gpu: "Intel Iris Xe",
      ram: "16GB",
      storage: "1TB SSD",
      display: "13.9-inch 3K Touch (3000x2000)",
      os: "Windows 11 Home",
      battery: "60Wh",
      weight: "1.33kg",
    },
    features: [
      "10-Point Touchscreen",
      "Harman Kardon Speakers",
      "Hidden Webcam",
    ],
    reviews: [],
  },
  {
    id: 15,
    name: "Alienware m15 R7",
    category: "laptop",
    price: 2199,
    colors: ["Silver", "Black", "white"],
    description:
      "High-performance gaming laptop with Intel i9-12900H and RTX 3070 Ti.",
    images: [
      "/images/laptops/Alienware m15 R7.jpg",
      "/images/laptops/Alienware m15 R7-2.jpg",
      "/images/laptops/Alienware m15 R7-3.jpg",
      "/images/laptops/Alienware m15 R7-4.jpg",
      "/images/laptops/Alienware m15 R7-5.jpg",
    ],
    brand: "Dell",
    stock: 25,
    rating: 4.9,
    specs: {
      cpu: "Intel Core i9-12900H",
      gpu: "NVIDIA RTX 3070 Ti (8GB)",
      ram: "32GB",
      storage: "2TB SSD",
      display: "15.6-inch QHD (2560x1440) 240Hz",
      os: "Windows 11 Pro",
      battery: "86Wh",
      weight: "2.5kg",
    },
    features: [
      "Cherry MX Mechanical Keyboard",
      "AlienFX Lighting",
      "Cryo-Tech Cooling",
    ],
    reviews: [],
  },
  {
    id: 16,
    name: "Framework Laptop",
    category: "laptop",
    price: 1399,
    colors: ["Silver", "Black", "white"],
    description:
      "Modular and repairable laptop with user-upgradable ports and components.",
    images: [
      "/images/laptops/Framework Laptop.jpg",
      "/images/laptops/Framework Laptop-2.jpg",
      "/images/laptops/Framework Laptop-4.jpg",
    ],
    brand: "Framework",
    stock: 60,
    rating: 4.5,
    specs: {
      cpu: "Intel Core i5-1240P",
      gpu: "Intel Iris Xe",
      ram: "16GB",
      storage: "512GB SSD",
      display: "13.5-inch 3:2 (2256x1504)",
      os: "Windows 11 Home",
      battery: "55Wh",
      weight: "1.3kg",
    },
    features: ["Modular Design", "DIY Upgrade Kits", "100% Recycled Packaging"],
    reviews: [],
  },
  {
    id: 17,
    name: "Xiaomi Mi Notebook Pro",
    category: "laptop",
    price: 1199,
    colors: ["Silver", "Black", "white"],
    description:
      "Premium aluminum laptop with 11th Gen Intel CPU and 65W fast charging.",
    images: [
      "/images/laptops/Xiaomi Mi Notebook Pro.jpg",
      "/images/laptops/Xiaomi Mi Notebook Pro-2.jpg",
      "/images/laptops/Xiaomi Mi Notebook Pro-3.jpg",
      "/images/laptops/Xiaomi Mi Notebook Pro-4.jpg",
      "/images/laptops/Xiaomi Mi Notebook Pro-5.jpg",
    ],
    brand: "Xiaomi",
    stock: 70,
    rating: 4.6,
    specs: {
      cpu: "Intel Core i7-11370H",
      gpu: "NVIDIA MX450 (2GB)",
      ram: "16GB",
      storage: "1TB SSD",
      display: "15.6-inch 3.5K OLED (3456x2160)",
      os: "Windows 11 Home",
      battery: "66Wh",
      weight: "1.8kg",
    },
    features: ["Dolby Atmos Speakers", "Thunderbolt 4", "Backlit Keyboard"],
    reviews: [],
  },
  {
    id: 18,
    name: "ASUS ZenBook Duo 14",
    category: "laptop",
    price: 1599,
    colors: ["Silver", "Black", "white"],
    description:
      "Dual-screen productivity laptop with 12.6-inch ScreenPad Plus.",
    images: [
      "/images/laptops/ASUS ZenBook Duo 14.jpg",
      "/images/laptops/ASUS ZenBook Duo 14-2.jpg",
      "/images/laptops/ASUS ZenBook Duo 14-3.jpg",
      "/images/laptops/ASUS ZenBook Duo 14-4.jpg",
      "/images/laptops/ASUS ZenBook Duo 14-5.jpg",
    ],
    brand: "ASUS",
    stock: 35,
    rating: 4.7,
    specs: {
      cpu: "Intel Core i7-1195G7",
      gpu: "NVIDIA MX450 (2GB)",
      ram: "16GB",
      storage: "1TB SSD",
      display: "14-inch FHD (1920x1080) + 12.6-inch ScreenPad",
      os: "Windows 11 Pro",
      battery: "70Wh",
      weight: "1.6kg",
    },
    features: ["Dual-Screen Design", "Active Pen Support", "ErgoLift Hinge"],
    reviews: [],
  },
  {
    id: 19,
    name: "Lenovo Legion 5 Pro",
    category: "laptop",
    price: 1899,
    colors: ["Silver", "Black", "white"],
    description:
      "Gaming powerhouse with AMD Ryzen 7 6800H and 165Hz QHD display.",
    images: [
      "/images/laptops/Lenovo Legion 5 Pro.jpg",
      "/images/laptops/Lenovo Legion 5 Pro-2.jpg",
      "/images/laptops/Lenovo Legion 5 Pro-3.jpg",
      "/images/laptops/Lenovo Legion 5 Pro-4.jpg",
      "/images/laptops/Lenovo Legion 5 Pro-5.jpg",
    ],
    brand: "Lenovo",
    stock: 50,
    rating: 4.8,
    specs: {
      cpu: "AMD Ryzen 7 6800H",
      gpu: "NVIDIA RTX 3070 (8GB)",
      ram: "32GB",
      storage: "1TB SSD",
      display: "16-inch QHD (2560x1600) 165Hz",
      os: "Windows 11 Home",
      battery: "80Wh",
      weight: "2.5kg",
    },
    features: ["RGB Keyboard", "Nahimic Audio", "Coldfront 4.0 Cooling"],
    reviews: [],
  },
  {
    id: 20,
    name: "Microsoft Surface Laptop Studio",
    category: "laptop",
    price: 2099,
    colors: ["Silver", "Black", "white"],
    description:
      "Versatile 2-in-1 laptop with dynamic hinge and Surface Slim Pen 2 support.",
    images: [
      "/images/laptops/Microsoft Surface Laptop Studio.jpg",
      "/images/laptops/Microsoft Surface Laptop Studio-2.jpg",
      "/images/laptops/Microsoft Surface Laptop Studio-3.jpg",
      "/images/laptops/Microsoft Surface Laptop Studio-4.jpg",
      "/images/laptops/Microsoft Surface Laptop Studio-5.jpg",
    ],
    brand: "Microsoft",
    stock: 30,
    rating: 4.9,
    specs: {
      cpu: "Intel Core i7-11370H",
      gpu: "NVIDIA RTX 3050 Ti (4GB)",
      ram: "32GB",
      storage: "2TB SSD",
      display: "14.4-inch PixelSense (2400x1600) 120Hz",
      os: "Windows 11 Pro",
      battery: "58Wh",
      weight: "1.8kg",
    },
    features: ["Studio Mode", "Haptic Touchpad", "Dolby Vision"],
    reviews: [],
  },

  {
    id: 21,
    name: "ASUS ROG Zephyrus G15",
    category: "laptop",
    price: 1899,
    colors: ["Silver", "Black", "white"],
    description:
      "Gaming laptop with AMD Ryzen 9 6900HS, RTX 3080, and 240Hz WQHD display.",
    images: [
      "/images/laptops/ASUS ROG Zephyrus G15.jpg",
      "/images/laptops/ASUS ROG Zephyrus G15-2.jpg",
      "/images/laptops/ASUS ROG Zephyrus G15-3.jpg",
      "/images/laptops/ASUS ROG Zephyrus G15-4.jpg",
      "/images/laptops/ASUS ROG Zephyrus G15-5.jpg",
    ],
    brand: "ASUS",
    stock: 40,
    rating: 4.9,
    specs: {
      cpu: "AMD Ryzen 9 6900HS",
      gpu: "NVIDIA RTX 3080 (16GB)",
      ram: "32GB",
      storage: "2TB SSD",
      display: "15.6-inch WQHD (2560x1440) 240Hz",
      os: "Windows 11 Pro",
      battery: "90Wh",
      weight: "1.9kg",
    },
    features: ["AniMe Matrix Lid", "RGB Keyboard", "Dolby Atmos"],
    reviews: [],
  },
  {
    id: 22,
    name: "ASUS ZenBook 14X OLED",
    category: "laptop",
    price: 1399,
    colors: ["Silver", "Black", "white"],
    description:
      "Ultra-slim laptop with 14-inch 4K OLED display and Intel Evo certification.",
    images: [
      "/images/laptops/ASUS ZenBook 14X OLED.jpg",
      "/images/laptops/ASUS ZenBook 14X OLED-2.jpg",
      "/images/laptops/ASUS ZenBook 14X OLED-3.jpg",
      "/images/laptops/ASUS ZenBook 14X OLED-4.jpg",
      "/images/laptops/ASUS ZenBook 14X OLED-5.jpg",
      "/images/laptops/ASUS ZenBook 14X OLED-6.jpg",
    ],
    brand: "ASUS",
    stock: 60,
    rating: 4.7,
    specs: {
      cpu: "Intel Core i7-1260P",
      gpu: "Intel Iris Xe",
      ram: "16GB",
      storage: "1TB SSD",
      display: "14-inch 4K OLED (3840x2400)",
      os: "Windows 11 Home",
      battery: "63Wh",
      weight: "1.4kg",
    },
    features: [
      "NumberPad 2.0",
      "Harman Kardon Audio",
      "Military-Grade Durability",
    ],
    reviews: [],
  },
  {
    id: 23,
    name: "ASUS TUF Dash F15",
    category: "laptop",
    price: 1299,
    colors: ["Silver", "Black", "white"],
    description:
      "Military-grade gaming laptop with Intel i7-12650H and RTX 3060.",
    images: [
      "/images/laptops/ASUS TUF Dash F15.jpg",
      "/images/laptops/ASUS TUF Dash F15-2.jpg",
      "/images/laptops/ASUS TUF Dash F15-3.jpg",
      "/images/laptops/ASUS TUF Dash F15-4.jpg",
      "/images/laptops/ASUS TUF Dash F15-5.jpg",
    ],
    brand: "ASUS",
    stock: 50,
    rating: 4.6,
    specs: {
      cpu: "Intel Core i7-12650H",
      gpu: "NVIDIA RTX 3060 (6GB)",
      ram: "16GB",
      storage: "512GB SSD",
      display: "15.6-inch FHD (1920x1080) 144Hz",
      os: "Windows 11 Home",
      battery: "76Wh",
      weight: "2kg",
    },
    features: [
      "MIL-STD-810H Certified",
      "RGB Lighting",
      "Self-Cleaning Cooling",
    ],
    reviews: [],
  },
  {
    id: 24,
    name: "ASUS VivoBook Pro 16X",
    category: "laptop",
    price: 1599,
    colors: ["Silver", "Black", "white"],
    description: "Creator laptop with 16-inch 4K OLED and AMD Ryzen 9 6900HX.",
    images: [
      "/images/laptops/ASUS VivoBook Pro 16X.jpg",
      "/images/laptops/ASUS VivoBook Pro 16X-2.jpg",
      "/images/laptops/ASUS VivoBook Pro 16X-3.jpg",
      "/images/laptops/ASUS VivoBook Pro 16X-4.jpg",
      "/images/laptops/ASUS VivoBook Pro 16X-5.jpg",
    ],
    brand: "ASUS",
    stock: 35,
    rating: 4.8,
    specs: {
      cpu: "AMD Ryzen 9 6900HX",
      gpu: "NVIDIA RTX 3050 Ti (4GB)",
      ram: "32GB",
      storage: "1TB SSD",
      display: "16-inch 4K OLED (3840x2400)",
      os: "Windows 11 Pro",
      battery: "90Wh",
      weight: "1.95kg",
    },
    features: [
      "DialPad Virtual Controller",
      "Pantone Validation",
      "ASUS Pen Support",
    ],
    reviews: [],
  },
  {
    id: 25,
    name: "ASUS ZenBook Flip 13",
    category: "laptop",
    price: 1199,
    colors: ["Silver", "Black", "white"],
    description:
      "2-in-1 convertible laptop with 360° hinge and 13.3-inch 4K OLED touchscreen.",
    images: [
      "/images/laptops/ASUS ZenBook Flip 13.webp",
      "/images/laptops/ASUS ZenBook Flip 13-2.jpg",
      "/images/laptops/ASUS ZenBook Flip 13-3.jpg",
      "/images/laptops/ASUS ZenBook Flip 13-4.jpg",
      "/images/laptops/ASUS ZenBook Flip 13-5.jpg",
    ],
    brand: "ASUS",
    stock: 45,
    rating: 4.5,
    specs: {
      cpu: "Intel Core i7-1165G7",
      gpu: "Intel Iris Xe",
      ram: "16GB",
      storage: "512GB SSD",
      display: "13.3-inch 4K OLED (3840x2400) Touch",
      os: "Windows 11 Home",
      battery: "67Wh",
      weight: "1.3kg",
    },
    features: ["Stylus Support", "ErgoLift Hinge", "HarmonyOS Compatibility"],
    reviews: [],
  },

  {
    id: 26,
    name: "Lenovo ThinkPad X1 Carbon Gen 10",
    category: "laptop",
    price: 1999,
    colors: ["Silver", "Black", "white"],
    description:
      "Ultra-light business laptop with Intel i7-1280P, 14-inch 4K display, and LTE connectivity.",
    images: [
      "/images/laptops/Lenovo ThinkPad X1 Carbon Gen 10.jpg",
      "/images/laptops/Lenovo ThinkPad X1 Carbon Gen 10-2.jpg",
      "/images/laptops/Lenovo ThinkPad X1 Carbon Gen 10-3.jpg",
      "/images/laptops/Lenovo ThinkPad X1 Carbon Gen 10-4.jpg",
    ],
    brand: "Lenovo",
    stock: 30,
    rating: 4.9,
    specs: {
      cpu: "Intel Core i7-1280P",
      gpu: "Intel Iris Xe",
      ram: "32GB",
      storage: "1TB SSD",
      display: "14-inch 4K UHD (3840x2400)",
      os: "Windows 11 Pro",
      battery: "57Wh",
      weight: "1.12kg",
    },
    features: ["Military-Grade Durability", "4G LTE", "Dolby Atmos Speakers"],
    reviews: [],
  },
  {
    id: 27,
    name: "Lenovo Legion 7i",
    category: "laptop",
    price: 2499,
    colors: ["Silver", "Black", "white"],
    description:
      "High-performance gaming laptop with Intel i9-12900HX and RTX 3080 Ti.",
    images: [
      "/images/laptops/Lenovo Legion 7i.jpg",
      "/images/laptops/Lenovo Legion 7i-2.jpg",
      "/images/laptops/Lenovo Legion 7i-3.jpg",
      "/images/laptops/Lenovo Legion 7i-4.jpg",
      "/images/laptops/Lenovo Legion 7i-5.jpg",
      "/images/laptops/Lenovo Legion 7i-6.jpg",
    ],
    brand: "Lenovo",
    stock: 25,
    rating: 4.8,
    specs: {
      cpu: "Intel Core i9-12900HX",
      gpu: "NVIDIA RTX 3080 Ti (16GB)",
      ram: "32GB",
      storage: "2TB SSD",
      display: "16-inch QHD (2560x1600) 240Hz",
      os: "Windows 11 Home",
      battery: "99.9Wh",
      weight: "2.5kg",
    },
    features: ["RGB Keyboard", "Vapor Chamber Cooling", "Nahimic Audio"],
    reviews: [],
  },
  {
    id: 28,
    name: "Lenovo Yoga 9i",
    category: "laptop",
    price: 1799,
    colors: ["Silver", "Black", "white"],
    description:
      "Premium 2-in-1 convertible laptop with 14-inch 4K OLED touchscreen and rotating soundbar.",
    images: [
      "/images/laptops/Lenovo Yoga 9i.jpg",
      "/images/laptops/Lenovo Yoga 9i-2.jpg",
      "/images/laptops/Lenovo Yoga 9i-3.jpg",
      "/images/laptops/Lenovo Yoga 9i-4.jpg",
      "/images/laptops/Lenovo Yoga 9i-5.jpg",
    ],
    brand: "Lenovo",
    stock: 40,
    rating: 4.7,
    specs: {
      cpu: "Intel Core i7-1260P",
      gpu: "Intel Iris Xe",
      ram: "16GB",
      storage: "1TB SSD",
      display: "14-inch 4K OLED (3840x2400) Touch",
      os: "Windows 11 Home",
      battery: "75Wh",
      weight: "1.37kg",
    },
    features: ["Rotating Soundbar", "Active Pen Support", "Aluminum Unibody"],
    reviews: [],
  },
  {
    id: 29,
    name: "Lenovo IdeaPad Slim 7 Pro",
    category: "laptop",
    price: 1299,
    colors: ["Silver", "Black", "white"],
    description:
      "Sleek and powerful laptop with AMD Ryzen 7 6800H and 14.5-inch 2.8K display.",
    images: [
      "/images/laptops/Lenovo IdeaPad Slim 7 Pro.jpg",
      "/images/laptops/Lenovo IdeaPad Slim 7 Pro-2.jpg",
      "/images/laptops/Lenovo IdeaPad Slim 7 Pro-3.jpg",
      "/images/laptops/Lenovo IdeaPad Slim 7 Pro-4.jpg",
      "/images/laptops/Lenovo IdeaPad Slim 7 Pro-5.jpg",
    ],
    brand: "Lenovo",
    stock: 50,
    rating: 4.6,
    specs: {
      cpu: "AMD Ryzen 7 6800H",
      gpu: "AMD Radeon Graphics",
      ram: "16GB",
      storage: "1TB SSD",
      display: "14.5-inch 2.8K (2880x1800) 90Hz",
      os: "Windows 11 Home",
      battery: "75Wh",
      weight: "1.45kg",
    },
    features: ["Dolby Vision", "Backlit Keyboard", "Fingerprint Reader"],
    reviews: [],
  },
  {
    id: 30,
    name: "Lenovo ThinkBook 16p Gen 4",
    category: "laptop",
    price: 1899,
    colors: ["Silver", "Black", "white"],
    description:
      "Creator laptop with AMD Ryzen 9 6900HX, RTX 3060, and 16-inch 2.5K display.",
    images: [
      "/images/laptops/Lenovo ThinkBook 16p Gen 4.jpg",
      "/images/laptops/Lenovo ThinkBook 16p Gen 4-5.jpg",
      "/images/laptops/Lenovo ThinkBook 16p Gen 4-6.jpg",
      "/images/laptops/Lenovo ThinkBook 16p Gen 4-4.jpg",
      "/images/laptops/Lenovo ThinkBook 16p Gen 4-3.jpg",
      "/images/laptops/Lenovo ThinkBook 16p Gen 4-2.jpg",
    ],
    brand: "Lenovo",
    stock: 35,
    rating: 4.8,
    specs: {
      cpu: "AMD Ryzen 9 6900HX",
      gpu: "NVIDIA RTX 3060 (6GB)",
      ram: "32GB",
      storage: "1TB SSD",
      display: "16-inch 2.5K (2560x1600) 165Hz",
      os: "Windows 11 Pro",
      battery: "90Wh",
      weight: "1.99kg",
    },
    features: ["Pantone Validation", "Dolby Atmos", "Privacy Shutter"],
    reviews: [],
  },

  {
    id: 31,
    name: "HP Spectre x360 14",
    category: "laptop",
    price: 1499,
    colors: ["Silver", "Black", "white"],
    description:
      "Premium 2-in-1 convertible with 13.5-inch 3K OLED display and 12th Gen Intel CPU.",
    brand: "HP",
    images: [
      "/images/laptops/HP Spectre x360 14.jpg",
      "/images/laptops/HP Spectre x360 14-2.jpg",
      "/images/laptops/HP Spectre x360 14-3.jpg",
      "/images/laptops/HP Spectre x360 14-4.jpg",
      "/images/laptops/HP Spectre x360 14-5.jpg",
      "/images/laptops/HP Spectre x360 14-6.jpg",
    ],
    stock: 45,
    rating: 4.8,
    specs: {
      cpu: "Intel Core i7-1255U",
      gpu: "Intel Iris Xe",
      ram: "16GB",
      storage: "1TB SSD",
      display: "13.5-inch 3K OLED (3000x2000) Touch",
      os: "Windows 11 Pro",
      battery: "66Wh",
      weight: "1.34kg",
    },
    features: ["360° Hinge", "Thunderbolt 4", "B&O Audio"],
    reviews: [],
  },
  {
    id: 32,
    name: "HP Omen 17",
    category: "laptop",
    price: 2199,
    colors: ["Silver", "Black", "white"],
    description: "Gaming powerhouse with Intel i9-13900HX and RTX 4080.",
    brand: "HP",
    images: [
      "/images/laptops/HP Omen 17.jpg",
      "/images/laptops/HP Omen 17-2.jpg",
      "/images/laptops/HP Omen 17-3.jpg",
      "/images/laptops/HP Omen 17-4.jpg",
      "/images/laptops/HP Omen 17-5.jpg",
    ],
    stock: 25,
    rating: 4.9,
    specs: {
      cpu: "Intel Core i9-13900HX",
      gpu: "NVIDIA RTX 4080 (12GB)",
      ram: "32GB",
      storage: "2TB SSD",
      display: "17.3-inch QHD (2560x1440) 240Hz",
      os: "Windows 11 Home",
      battery: "83Wh",
      weight: "3.2kg",
    },
    features: ["RGB Keyboard", "OMEN Tempest Cooling", "Mini-LED Display"],
    reviews: [],
  },
  {
    id: 33,
    name: "HP Envy 16",
    category: "laptop",
    price: 1899,
    colors: ["Silver", "Black", "white"],
    description: "Creator laptop with 16-inch 4K OLED and RTX 4060.",
    brand: "HP",
    images: [
      "/images/laptops/HP Envy 16.jpg",
      "/images/laptops/HP Envy 16-2.jpg",
      "/images/laptops/HP Envy 16-3.jpg",
      "/images/laptops/HP Envy 16-4.jpg",
    ],
    stock: 30,
    rating: 4.7,
    specs: {
      cpu: "Intel Core i7-13700H",
      gpu: "NVIDIA RTX 4060 (8GB)",
      ram: "32GB",
      storage: "1TB SSD",
      display: "16-inch 4K OLED (3840x2400)",
      os: "Windows 11 Pro",
      battery: "83Wh",
      weight: "2.3kg",
    },
    features: ["Pantone Validation", "HP Rechargeable Pen", "Quad Speakers"],
    reviews: [],
  },
  {
    id: 34,
    name: "HP Pavilion Aero 13",
    category: "laptop",
    price: 899,
    colors: ["Silver", "Black", "white"],
    description:
      "Ultra-light laptop with AMD Ryzen 7 and 13.3-inch 2.5K display.",
    brand: "HP",
    images: [
      "/images/laptops/HP Pavilion Aero 13.jpg",
      "/images/laptops/HP Pavilion Aero 13-2.jpg",
      "/images/laptops/HP Pavilion Aero 13-3.jpg",
      "/images/laptops/HP Pavilion Aero 13-4.jpg",
      "/images/laptops/HP Pavilion Aero 13-5.jpg",
    ],
    stock: 70,
    rating: 4.5,
    specs: {
      cpu: "AMD Ryzen 7 7735U",
      gpu: "AMD Radeon Graphics",
      ram: "16GB",
      storage: "512GB SSD",
      display: "13.3-inch 2.5K (2560x1600)",
      os: "Windows 11 Home",
      battery: "43Wh",
      weight: "0.98kg",
    },
    features: ["Magnesium-Aluminum Body", "Wi-Fi 6E", "Backlit Keyboard"],
    reviews: [],
  },
  {
    id: 35,
    name: "HP ZBook Fury 16 G9",
    category: "laptop",
    price: 3499,
    colors: ["Silver", "Black", "white"],
    description: "Workstation laptop with Intel Xeon CPU and RTX A5500.",
    brand: "HP",
    images: [
      "/images/laptops/HP ZBook Fury 16 G9.jpg",
      "/images/laptops/HP ZBook Fury 16 G9-2.jpg",
      "/images/laptops/HP ZBook Fury 16 G9-3.jpg",
      "/images/laptops/HP ZBook Fury 16 G9-4.jpg",
      "/images/laptops/HP ZBook Fury 16 G9-5.jpg",
    ],
    stock: 15,
    rating: 4.9,
    specs: {
      cpu: "Intel Xeon W-11955M",
      gpu: "NVIDIA RTX A5500 (16GB)",
      ram: "64GB",
      storage: "4TB SSD",
      display: "16-inch 4K UHD (3840x2400)",
      os: "Windows 11 Pro",
      battery: "94Wh",
      weight: "2.5kg",
    },
    features: ["ISV Certified", "ECC Memory", "HP Sure View Privacy"],
    reviews: [],
  },
  {
    id: 36,
    name: "MSI Stealth 16 Studio",
    category: "laptop",
    price: 2599,
    colors: ["Silver", "Black", "white"],
    description: "Slim gaming laptop with Intel i9-13900H and RTX 4090.",
    brand: "MSI",
    images: [
      "/images/laptops/MSI Stealth 16 Studio.jpg",
      "/images/laptops/MSI Stealth 16 Studio-2.jpg",
      "/images/laptops/MSI Stealth 16 Studio-3.jpg",
      "/images/laptops/MSI Stealth 16 Studio-4.jpg",
      "/images/laptops/MSI Stealth 16 Studio-5.jpg",
    ],
    stock: 20,
    rating: 4.9,
    specs: {
      cpu: "Intel Core i9-13900H",
      gpu: "NVIDIA RTX 4090 (16GB)",
      ram: "64GB",
      storage: "2TB SSD",
      display: "16-inch 4K UHD (3840x2400) 120Hz",
      os: "Windows 11 Pro",
      battery: "99.9Wh",
      weight: "2.1kg",
    },
    features: ["Per-Key RGB", "Thunderbolt 4", "Cooler Boost 5"],
    reviews: [],
  },
  {
    id: 37,
    name: "MSI Raider GE78 HX",
    category: "laptop",
    price: 2999,
    colors: ["Silver", "Black", "white"],
    description:
      "Flagship gaming laptop with 17-inch Mini-LED display and Cherry MX keyboard.",
    brand: "MSI",
    images: [
      "/images/laptops/MSI Raider GE78 HX.jpg",
      "/images/laptops/MSI Raider GE78 HX-2.jpg",
      "/images/laptops/MSI Raider GE78 HX-3.jpg",
      "/images/laptops/MSI Raider GE78 HX-4.jpg",
      "/images/laptops/MSI Raider GE78 HX-5.jpg",
    ],
    stock: 10,
    rating: 5.0,
    specs: {
      cpu: "Intel Core i9-13980HX",
      gpu: "NVIDIA RTX 4090 (16GB)",
      ram: "64GB",
      storage: "4TB SSD",
      display: "17-inch 4K Mini-LED (3840x2400) 144Hz",
      os: "Windows 11 Pro",
      battery: "99.9Wh",
      weight: "3.3kg",
    },
    features: [
      "Mech Cherry MX Keyboard",
      "Dynamic Cooler Boost",
      "Mystic Light Bar",
    ],
    reviews: [],
  },
  {
    id: 38,
    name: "MSI Katana 15",
    category: "laptop",
    price: 1299,
    colors: ["Silver", "Black", "white"],
    description: "Budget gaming laptop with Intel i7-13700H and RTX 4060.",
    brand: "MSI",
    images: [
      "/images/laptops/MSI Katana 15.jpg",
      "/images/laptops/MSI Katana 15-2.jpg",
      "/images/laptops/MSI Katana 15-3.jpg",
      "/images/laptops/MSI Katana 15-4.jpg",
      "/images/laptops/MSI Katana 15-5.jpg",
      "/images/laptops/MSI Katana 15-6.jpg",
    ],
    stock: 50,
    rating: 4.6,
    specs: {
      cpu: "Intel Core i7-13700H",
      gpu: "NVIDIA RTX 4060 (8GB)",
      ram: "16GB",
      storage: "1TB SSD",
      display: "15.6-inch FHD (1920x1080) 144Hz",
      os: "Windows 11 Home",
      battery: "53.5Wh",
      weight: "2.25kg",
    },
    features: ["Cooler Boost 5", "Hi-Res Audio", "Anti-Glare Display"],
    reviews: [],
  },
  {
    id: 39,
    name: "MSI Prestige 14 Evo",
    category: "laptop",
    price: 1499,
    colors: ["Silver", "Black", "white"],
    description:
      "Ultrabook with Intel Evo certification and 14-inch 2.8K display.",
    brand: "MSI",
    images: [
      "/images/laptops/MSI Prestige 14 Evo.jpg",
      "/images/laptops/MSI Prestige 14 Evo-2.jpg",
      "/images/laptops/MSI Prestige 14 Evo-3.jpg",
      "/images/laptops/MSI Prestige 14 Evo-4.jpg",
      "/images/laptops/MSI Prestige 14 Evo-5.jpg",
      "/images/laptops/MSI Prestige 14 Evo-6.jpg",
    ],
    stock: 40,
    rating: 4.7,
    specs: {
      cpu: "Intel Core i7-1360P",
      gpu: "Intel Iris Xe",
      ram: "32GB",
      storage: "1TB SSD",
      display: "14-inch 2.8K OLED (2880x1800)",
      os: "Windows 11 Pro",
      battery: "72Wh",
      weight: "1.29kg",
    },
    features: [
      "100% DCI-P3",
      "Fingerprint Sensor",
      "Military-Grade Durability",
    ],
    reviews: [],
  },
  {
    id: 40,
    name: "MSI Creator Z16P",
    category: "laptop",
    price: 2799,
    colors: ["Silver", "Black", "white"],
    description: "Creator laptop with 16-inch 4K Touch display and RTX 4080.",
    brand: "MSI",
    images: [
      "/images/laptops/MSI Creator Z16P.jpg",
      "/images/laptops/MSI Creator Z16P-2.jpg",
      "/images/laptops/MSI Creator Z16P-3.jpg",
      "/images/laptops/MSI Creator Z16P-4.jpg",
    ],
    stock: 15,
    rating: 4.8,
    specs: {
      cpu: "Intel Core i9-13900H",
      gpu: "NVIDIA RTX 4080 (12GB)",
      ram: "64GB",
      storage: "2TB SSD",
      display: "16-inch 4K Touch (3840x2400)",
      os: "Windows 11 Pro",
      battery: "90Wh",
      weight: "2.4kg",
    },
    features: ["Calman Verified", "True Pixel Display", "MSI Pen Support"],
    reviews: [],
  },
];

export const mobile = [
  {
    id: 41,
    name: "iPhone 15 Pro",
    category: "mobile",
    price: 999,
    colors: [
      "black titanium",
      "white titanium",
      "blue titanium",
      "natural titanium",
    ],
    description:
      "Apple's flagship phone with titanium frame, A17 Bionic chip, and 48MP camera.",
    brand: "Apple",
    images: [
      "/images/mobiles/iPhone 15 Pro.jpg",
      "/images/mobiles/iPhone 15 Pro-blue titanium.jpg",
      "/images/mobiles/iPhone 15 Pro-white titanium.jpg",
      "/images/mobiles/iPhone 15 Pro-natural titanium.jpg",
      "/images/mobiles/iPhone 15 Pro-Colection.jpg",
    ],
    stock: 150,
    rating: 4.8,
    specs: {
      chipset: "A17 Bionic",
      ram: "8GB",
      storage: "256GB",
      display: "6.1-inch Super Retina XDR (2556x1179)",
      camera: "48MP (Main) + 12MP (Ultra Wide) + 12MP (Telephoto)",
      battery: "3274mAh (Up to 23 hours)",
      os: "iOS 17",
      network: "5G, eSIM",
    },
    features: ["IP68 water resistance", "Ceramic Shield", "Wireless charging"],
    reviews: [],
  },
  {
    id: 42,
    name: "Samsung Galaxy S23",
    category: "mobile",
    price: 849,
    colors: ["Cream", "Phantom Black", "Green", "Lavender"],
    description:
      "Samsung's flagship with Snapdragon 8 Gen 2, 120Hz AMOLED display, and 50MP camera.",
    brand: "Samsung",
    images: [
      "/images/mobiles/Samsung Galaxy S23.jpg",
      "/images/mobiles/Samsung Galaxy S23-cream.jpg",
      "/images/mobiles/samsung galaxy s23-Green.jpg",
      "/images/mobiles/Samsung Galaxy S23-Lavender.jpg",
      "/images/mobiles/Samsung Galaxy S23-Phantom Black.jpg",
    ],
    stock: 120,
    rating: 4.7,
    specs: {
      chipset: "Snapdragon 8 Gen 2",
      ram: "8GB",
      storage: "256GB",
      display: "6.1-inch Dynamic AMOLED (2340x1080)",
      camera: "50MP (Main) + 12MP (Ultra Wide) + 10MP (Telephoto)",
      battery: "3900mAh (45W fast charging)",
      os: "Android 13",
    },
    features: ["Gorilla Glass Victus 2", "IP68 rating", "Wireless PowerShare"],
    reviews: [
      {
        user: "Alice Johnson",
        rating: 5,
        comment: "Smooth performance and stunning display!",
      },
    ],
  },
  {
    id: 43,
    name: "OnePlus 11",
    category: "mobile",
    price: 799,
    colors: ["Titan Black", "Eternal Green", "Jupiter Rock", "Lavender"],
    description:
      "Flagship phone with 100W fast charging, 2K AMOLED display, and Hasselblad camera.",
    brand: "OnePlus",
    images: [
      "/images/mobiles/OnePlus 11.jpg",
      "/images/mobiles/OnePlus 11-Eternal Green.jpg",
      "/images/mobiles/OnePlus 11-Jupiter Rock.jpg",
      "/images/mobiles/OnePlus 11-Lavender.jpg",
    ],
    stock: 130,
    rating: 4.8,
    specs: {
      chipset: "Snapdragon 8 Gen 2",
      ram: "16GB",
      storage: "256GB",
      display: "6.7-inch AMOLED (3216x1440)",
      camera: "50MP (Main) + 48MP (Ultra Wide) + 32MP (Telephoto)",
      battery: "5000mAh (100W SUPERVOOC)",
      os: "OxygenOS 13 (Android 13)",
    },
    features: [
      "In-display fingerprint sensor",
      "Aluminum frame",
      "Dolby Atmos",
    ],
    reviews: [
      {
        user: "Mike Brown",
        rating: 5,
        comment: "Blazing-fast charging and premium build!",
      },
    ],
  },

  {
    id: 44,
    name: "Xiaomi Mi 12",
    category: "mobile",
    price: 599,
    colors: ["Gray", "Blue", "Purple", "Green"],
    description:
      "Affordable flagship with Snapdragon 8 Gen 1, AMOLED display, and 50MP camera.",
    brand: "Xiaomi",
    images: [
      "/images/mobiles/Xiaomi Mi 12.webp",
      "/images/mobiles/Xiaomi Mi 12-gray.jpg",
      "/images/mobiles/Xiaomi Mi 12-Green.jpg",
      "/images/mobiles/Xiaomi Mi 12-purple.jpg",
      "/images/mobiles/Xiaomi Mi 12-colection.jpg",
    ],
    stock: 180,
    rating: 4.6,
    specs: {
      chipset: "Snapdragon 8 Gen 1",
      ram: "8GB",
      storage: "128GB",
      display: "6.28-inch AMOLED (2400x1080)",
      camera: "50MP (Main) + 13MP (Ultra Wide)",
      battery: "4500mAh (67W fast charging)",
      os: "MIUI 14 (Android 13)",
    },
    features: [
      "In-display fingerprint",
      "Stereo speakers",
      "Corning Gorilla Glass Victus",
    ],
    reviews: [],
  },
  {
    id: 45,
    name: "Oppo Find X6 Pro",
    category: "mobile",
    price: 1099,
    colors: ["Black", "Green", "Brown"],
    description:
      "Flagship phone with Sony IMX989 1-inch sensor, Snapdragon 8 Gen 2, and 100W charging.",
    brand: "Oppo",
    images: [
      "/images/mobiles/oppo find x6 pro.jpg",
      "/images/mobiles/Oppo Find X6 Pro-brown.jpg",
      "/images/mobiles/Oppo Find X6 Pro-green.jpg",
    ],
    stock: 100,
    rating: 4.8,
    specs: {
      chipset: "Snapdragon 8 Gen 2",
      ram: "12GB",
      storage: "256GB",
      display: "6.7-inch LTPO AMOLED (3216x1440)",
      camera: "50MP (Main) + 50MP (Ultra Wide) + 50MP (Telephoto)",
      battery: "5000mAh (100W SUPERVOOC)",
      os: "ColorOS 13 (Android 13)",
    },
    features: ["IP68 rating", "Periscope lens", "Vapor cooling system"],
    reviews: [],
  },
  {
    id: 46,
    name: "Vivo V27 Pro",
    category: "mobile",
    price: 599,
    colors: ["Magic Blue", "Noble Black"],
    description:
      "Mid-range phone with 50MP selfie camera, AMOLED display, and MediaTek Dimensity 8200.",
    brand: "Vivo",
    images: [
      "/images/mobiles/Vivo V27 Pro.jpg",
      "/images/mobiles/Vivo V27 Pro-nobleBlack.jpg",
    ],
    stock: 150,
    rating: 4.7,
    specs: {
      chipset: "MediaTek Dimensity 8200",
      ram: "8GB",
      storage: "128GB",
      display: "6.78-inch AMOLED (2400x1080)",
      camera: "50MP (Main) + 8MP (Ultra Wide) + 2MP (Macro)",
      battery: "4600mAh (66W fast charging)",
      os: "Funtouch OS 13 (Android 13)",
    },
    features: [
      "50MP front camera",
      "7.4mm slim design",
      "In-display fingerprint",
    ],
    reviews: [],
  },
  {
    id: 47,
    name: "Sony Xperia 1 IV",
    category: "mobile",
    price: 1199,
    colors: ["Black", "Violet", "White"],
    description:
      "Premium phone with 4K HDR OLED display, triple Zeiss cameras, and Snapdragon 8 Gen 1.",
    brand: "Sony",
    images: [
      "/images/mobiles/Sony Xperia 1 IV.jpg",
      "/images/mobiles/Sony Xperia 1 IV-black.jpg",
      "/images/mobiles/Sony Xperia 1 IV-violet.jpg",
      "/images/mobiles/Sony Xperia 1 IV-white.jpg",
    ],
    stock: 90,
    rating: 4.9,
    specs: {
      chipset: "Snapdragon 8 Gen 1",
      ram: "12GB",
      storage: "256GB",
      display: "6.5-inch 4K HDR OLED (3840x1644)",
      camera: "12MP (Main) × 3 (Zeiss optics)",
      battery: "5000mAh (30W charging)",
      os: "Android 13",
    },
    features: ["MicroSD slot", "3.5mm headphone jack", "IP68 rating"],
    reviews: [],
  },
  {
    id: 48,
    name: "Realme GT 2 Pro",
    category: "mobile",
    price: 749,
    colors: ["Paper White", "Paper Green", "Steel Black", "Titanium Blue"],
    description:
      "Powerful phone with Snapdragon 8 Gen 1, 120Hz AMOLED display, and 65W fast charging.",
    brand: "Realme",
    images: [
      "/images/mobiles/Realme GT 2 Pro.jpg",
      "/images/mobiles/Realme GT 2 Pro-paperGreen.jpg",
      "/images/mobiles/Realme GT 2 Pro-stillBlack.jpg",
      "/images/mobiles/Realme GT 2 Pro-colection.avif",
    ],
    stock: 110,
    rating: 4.6,
    specs: {
      chipset: "Snapdragon 8 Gen 1",
      ram: "12GB",
      storage: "256GB",
      display: "6.7-inch AMOLED (3216x1440) 120Hz",
      camera: "50MP (Main) + 50MP (Ultra Wide) + 40x microscope",
      battery: "5000mAh (65W SUPERVOOC)",
      os: "Realme UI 3.0 (Android 12)",
    },
    features: ["Biodegradable design", "Steam cooling", "Dolby Vision"],
    reviews: [],
  },
  {
    id: 49,
    name: "Motorola Edge 30 Ultra",
    category: "mobile",
    price: 899,
    colors: ["Interstellar Black", " Starlight White"],
    description:
      "Flagship phone with 200MP camera, 144Hz pOLED display, and 125W fast charging.",
    brand: "Motorola",
    images: [
      "/images/mobiles/Motorola Edge 30 Ultra.jpg",
      "/images/mobiles/Motorola Edge 30 Ultra-white.jpg",
    ],
    stock: 85,
    rating: 4.7,
    specs: {
      chipset: "Snapdragon 8+ Gen 1",
      ram: "12GB",
      storage: "512GB",
      display: "6.67-inch pOLED (2400x1080) 144Hz",
      camera: "200MP (Main) + 50MP (Ultra Wide) + 12MP (Telephoto)",
      battery: "4610mAh (125W TurboPower)",
      os: "Android 13",
    },
    features: [
      "IP52 splash resistance",
      "Stereo speakers",
      "Ready For platform",
    ],
    reviews: [],
  },

  {
    id: 50,
    name: "Samsung Galaxy S24 Ultra",
    category: "mobile",
    price: 1199,
    colors: [
      "Titanium Black",
      "Titanium Grey",
      "Titanium Violet",
      "Titanium Yellow",
    ],
    description:
      "Samsung's flagship phone with Snapdragon 8 Gen 3, 200MP camera, and S Pen support.",
    brand: "Samsung",
    images: [
      "/images/mobiles/Samsung Galaxy S24 Ultra.webp",
      "/images/mobiles/Samsung Galaxy S24 Ultra-black.jpg",
      "/images/mobiles/Samsung Galaxy S24 Ultra-Titanium Grey.jpg",
      "/images/mobiles/Samsung Galaxy S24 Ultra-Titanium Violet.jpg",
      "/images/mobiles/Samsung Galaxy S24 Ultra-TitaniumYellow.jpg",
    ],
    stock: 200,
    rating: 4.9,
    specs: {
      chipset: "Snapdragon 8 Gen 3",
      ram: "12GB",
      storage: "512GB",
      display: "6.8-inch Dynamic AMOLED 2X (3088x1440)",
      camera:
        "200MP (Main) + 12MP (Ultra Wide) + 10MP (Telephoto) + 10MP (Periscope)",
      battery: "5000mAh (Up to 30 hours)",
      os: "Android 14 (One UI 6)",
      network: "5G, Dual SIM",
    },
    features: ["S Pen support", "IP68 water resistance", "120Hz refresh rate"],
    reviews: [],
  },
  {
    id: 51,
    name: "Samsung Galaxy S24+",
    category: "mobile",
    price: 999,
    colors: [
      "Titanium Black",
      "Titanium Grey",
      "Titanium Violet",
      "Titanium Yellow",
    ],
    description:
      "A premium smartphone with Snapdragon 8 Gen 3, 50MP camera, and 120Hz AMOLED display.",
    brand: "Samsung",
    images: [
      "/images/mobiles/Samsung Galaxy S24+.avif",
      "/images/mobiles/Samsung Galaxy S24+-gray.jpg",
      "/images/mobiles/Samsung Galaxy S24+-Violet.jpg",
      "/images/mobiles/Samsung Galaxy S24+-Yellow.jpg",
      "/images/mobiles/Samsung Galaxy S24+-Colection.jpg",
    ],
    stock: 180,
    rating: 4.8,
    specs: {
      chipset: "Snapdragon 8 Gen 3",
      ram: "8GB",
      storage: "256GB",
      display: "6.7-inch Dynamic AMOLED 2X (3120x1440)",
      camera: "50MP (Main) + 12MP (Ultra Wide) + 10MP (Telephoto)",
      battery: "4700mAh (Up to 28 hours)",
      os: "Android 14 (One UI 6)",
      network: "5G, Dual SIM",
    },
    features: [
      "120Hz refresh rate",
      "Gorilla Glass Victus 2",
      "Wireless charging",
    ],
    reviews: [],
  },
  {
    id: 52,
    name: "Samsung Galaxy S24",
    category: "mobile",
    price: 799,
    colors: ["Amber Yellow", "Marble Gray", "Cobalt Violet", "Onyx Black"],
    description:
      "Compact flagship with Snapdragon 8 Gen 3, 50MP main camera, and fast charging.",
    brand: "Samsung",
    images: [
      "/images/mobiles/Samsung Galaxy S24.webp",
      "/images/mobiles/Samsung Galaxy S24-Amber Yellow.jpg",
      "/images/mobiles/Samsung Galaxy S24-CobaltVoilet.jpg",
      "/images/mobiles/Samsung Galaxy S24-MurbleGray.jpg",
      "/images/mobiles/Samsung Galaxy S24-onyxBlack.jpg",
    ],
    stock: 220,
    rating: 4.7,
    specs: {
      chipset: "Snapdragon 8 Gen 3",
      ram: "8GB",
      storage: "128GB",
      display: "6.1-inch Dynamic AMOLED 2X (2340x1080)",
      camera: "50MP (Main) + 12MP (Ultra Wide) + 10MP (Telephoto)",
      battery: "4000mAh (Up to 24 hours)",
      os: "Android 14 (One UI 6)",
      network: "5G, Dual SIM",
    },
    features: [
      "120Hz refresh rate",
      "Gorilla Glass Victus 2",
      "Wireless charging",
    ],
    reviews: [],
  },
  {
    id: 53,
    name: "Samsung Galaxy Z Fold 5",
    category: "mobile",
    price: 1799,
    colors: ["Icy Blue", "Phantom Black", "Cream"],
    description:
      "Foldable flagship with Snapdragon 8 Gen 2, large inner display, and multitasking features.",
    brand: "Samsung",
    images: [
      "/images/mobiles/Samsung Galaxy Z Fold 5.webp",
      "/images/mobiles/Samsung Galaxy Z Fold 5-Cream.jpg",
      "/images/mobiles/Samsung Galaxy Z Fold 5-icyBlue.jpg",
      "/images/mobiles/Samsung Galaxy Z Fold 5-PhantomBlack.jpg",
    ],
    stock: 100,
    rating: 4.8,
    specs: {
      chipset: "Snapdragon 8 Gen 2",
      ram: "12GB",
      storage: "512GB",
      display: "7.6-inch Dynamic AMOLED 2X (2176x1812)",
      camera: "50MP (Main) + 12MP (Ultra Wide) + 10MP (Telephoto)",
      battery: "4400mAh (Up to 27 hours)",
      os: "Android 13 (One UI 5.1)",
      network: "5G, Dual SIM",
    },
    features: ["Foldable display", "S Pen support", "IPX8 water resistance"],
    reviews: [],
  },

  {
    id: 54,
    name: "Samsung Galaxy Z Flip 5",
    category: "mobile",
    price: 999,
    colors: ["Graphite", "Mint", "Lavender", "Cream"],
    description:
      "Stylish foldable phone with a compact design, Snapdragon 8 Gen 2, and 120Hz AMOLED display.",
    brand: "Samsung",
    images: [
      "/images/mobiles/Samsung Galaxy Z Flip 5.jpg",
      "/images/mobiles/Samsung Galaxy Z Flip 5-Cream.jpg",
      "/images/mobiles/Samsung Galaxy Z Flip 5-Graphite.jpg",
      "/images/mobiles/Samsung Galaxy Z Flip 5-Lavender.jpg",
      "/images/mobiles/Samsung Galaxy Z Flip 5-Mint.jpg",
    ],
    stock: 150,
    rating: 4.6,
    specs: {
      chipset: "Snapdragon 8 Gen 2",
      ram: "8GB",
      storage: "256GB",
      display: "6.7-inch Dynamic AMOLED 2X (2640x1080)",
      camera: "12MP (Main) + 12MP (Ultra Wide)",
      battery: "3700mAh (Up to 20 hours)",
      os: "Android 13 (One UI 5.1)",
      network: "5G, Dual SIM",
    },
    features: [
      "Foldable display",
      "Cover screen customization",
      "Wireless charging",
    ],
    reviews: [],
  },
  {
    id: 55,
    name: "Samsung Galaxy A74 5G",
    category: "mobile",
    price: 549,
    colors: ["Gray", "Mint", "White"],
    description:
      "Mid-range smartphone with Snapdragon 778G, 108MP camera, and 120Hz AMOLED display.",
    brand: "Samsung",
    images: ["/images/mobiles/Samsung Galaxy A74 5G-white.jpeg"],
    stock: 300,
    rating: 4.5,
    specs: {
      chipset: "Snapdragon 778G",
      ram: "8GB",
      storage: "128GB",
      display: "6.7-inch Super AMOLED Plus (2400x1080)",
      camera: "108MP (Main) + 12MP (Ultra Wide) + 5MP (Macro)",
      battery: "5000mAh (Up to 48 hours)",
      os: "Android 13 (One UI 5)",
      network: "5G, Dual SIM",
    },
    features: ["120Hz refresh rate", "Stereo speakers", "Fast charging 25W"],
    reviews: [],
  },
  {
    id: 56,
    name: "Samsung Galaxy A54 5G",
    category: "mobile",
    price: 449,
    colors: ["Graphite", "White", "Violet", "Lime"],
    description:
      "Affordable 5G smartphone with Exynos 1380, 50MP main camera, and long battery life.",
    brand: "Samsung",
    images: [
      "/images/mobiles/Samsung Galaxy A54 5G.jpg",
      "/images/mobiles/Samsung Galaxy A54 5G-Lime.jpg",
      "/images/mobiles/Samsung Galaxy A54 5G-Violet.jpg",
      "/images/mobiles/Samsung Galaxy A54 5G-white.jpg",
    ],
    stock: 350,
    rating: 4.4,
    specs: {
      chipset: "Exynos 1380",
      ram: "6GB",
      storage: "128GB",
      display: "6.4-inch Super AMOLED (2340x1080)",
      camera: "50MP (Main) + 12MP (Ultra Wide) + 5MP (Macro)",
      battery: "5000mAh (Up to 50 hours)",
      os: "Android 13 (One UI 5.1)",
      network: "5G, Dual SIM",
    },
    features: [
      "IP67 water resistance",
      "Stereo speakers",
      "120Hz refresh rate",
    ],
    reviews: [],
  },
  {
    id: 57,
    name: "Samsung Galaxy M54",
    category: "mobile",
    price: 399,
    colors: ["Silver", "Dark Blue"],
    description:
      "Budget-friendly smartphone with Exynos 1380, 108MP camera, and large battery.",
    brand: "Samsung",
    images: [
      "/images/mobiles/Samsung Galaxy M54.jpg",
      "/images/mobiles/Samsung Galaxy M54-darkBlue.jpg",
      "/images/mobiles/Samsung Galaxy M54-Colection.jpg",
    ],
    stock: 280,
    rating: 4.3,
    specs: {
      chipset: "Exynos 1380",
      ram: "8GB",
      storage: "256GB",
      display: "6.7-inch Super AMOLED Plus (2400x1080)",
      camera: "108MP (Main) + 8MP (Ultra Wide) + 2MP (Macro)",
      battery: "6000mAh (Up to 72 hours)",
      os: "Android 13 (One UI 5.1)",
      network: "5G, Dual SIM",
    },
    features: ["Large battery", "Fast charging 25W", "120Hz refresh rate"],
    reviews: [],
  },
  {
    id: 58,
    name: "Samsung Galaxy A34 5G",
    category: "mobile",
    price: 349,
    colors: ["Lime", "Graphite", "Silver", "Violet"],
    description:
      "Affordable 5G smartphone with Dimensity 1080, 48MP camera, and AMOLED display.",
    brand: "Samsung",
    images: [
      "/images/mobiles/Samsung Galaxy A34 5G.jpg",
      "/images/mobiles/Samsung Galaxy A34 5G-Lime.jpg",
      "/images/mobiles/Samsung Galaxy A34 5G-Silver.jpg",
      "/images/mobiles/Samsung Galaxy A34 5G-Violet.jpg",
      "/images/mobiles/Samsung Galaxy A34 5G-Colection.jpg",
    ],
    stock: 400,
    rating: 4.2,
    specs: {
      chipset: "Dimensity 1080",
      ram: "6GB",
      storage: "128GB",
      display: "6.6-inch Super AMOLED (2340x1080)",
      camera: "48MP (Main) + 8MP (Ultra Wide) + 5MP (Macro)",
      battery: "5000mAh (Up to 48 hours)",
      os: "Android 13 (One UI 5)",
      network: "5G, Dual SIM",
    },
    features: ["120Hz refresh rate", "Stereo speakers", "Fast charging 25W"],
    reviews: [],
  },
  {
    id: 59,
    name: "Samsung Galaxy A14 5G",
    category: "mobile",
    price: 249,
    colors: ["Black", "Light Green", "Silver", "Dark Red"],
    description:
      "Entry-level 5G smartphone with Dimensity 700, 50MP camera, and long battery life.",
    brand: "Samsung",
    images: [
      "/images/mobiles/Samsung Galaxy A14 5G.jpg",
      "/images/mobiles/Samsung Galaxy A14 5G-DrakRed.jpg",
      "/images/mobiles/Samsung Galaxy A14 5G-Graphite.jpg",
      "/images/mobiles/Samsung Galaxy A14 5G-lightGreen.jpg",
      "/images/mobiles/Samsung Galaxy A14 5G-Colection.jpg",
    ],
    stock: 500,
    rating: 4.0,
    specs: {
      chipset: "Dimensity 700",
      ram: "4GB",
      storage: "64GB",
      display: "6.6-inch PLS LCD (2408x1080)",
      camera: "50MP (Main) + 2MP (Depth) + 2MP (Macro)",
      battery: "5000mAh (Up to 48 hours)",
      os: "Android 13 (One UI Core 5)",
      network: "5G, Dual SIM",
    },
    features: [
      "Affordable 5G support",
      "Long battery life",
      "Side-mounted fingerprint scanner",
    ],
    reviews: [],
  },

  {
    id: 60,
    name: "Xiaomi 13 Ultra",
    category: "mobile",
    price: 1099,
    colors: ["Black", "Olive Green", "White", "Orange", "Yellow", "Blue"],
    description:
      "Flagship smartphone with Leica quad-camera, Snapdragon 8 Gen 2, and 2K AMOLED display.",
    images: [
      "/images/mobiles/Xiaomi 13 Ultra.jpg",
      "/images/mobiles/Xiaomi 13 Ultra-Black.jpg",
      "/images/mobiles/Xiaomi 13 Ultra-OliveGreen.jpg",
      "/images/mobiles/Xiaomi 13 Ultra-Orange.jpg",
      "/images/mobiles/Xiaomi 13 Ultra-White.jpg",
    ],
    brand: "Xiaomi",
    stock: 60,
    rating: 4.8,
    specs: {
      chipset: "Snapdragon 8 Gen 2",
      ram: "12GB",
      storage: "256GB",
      display: "6.73-inch AMOLED (3200x1440) 120Hz",
      camera:
        "50MP (Leica Main) + 50MP (Ultra Wide) + 50MP (Telephoto) + 50MP (Periscope)",
      battery: "5000mAh (90W Fast Charging)",
      os: "Android 13 (MIUI 14)",
      network: "5G",
    },
    features: ["IP68 Rating", "Leica Optics", "Dolby Atmos"],
    reviews: [],
  },
  {
    id: 61,
    name: "Xiaomi 13T Pro",
    category: "mobile",
    price: 699,
    colors: ["Alpine Blue", "Meadow Green", "Black"],
    description:
      "High-performance phone with MediaTek Dimensity 9200+ and 200MP camera.",
    images: [
      "/images/mobiles/Xiaomi 13T Pro.jpg",
      "/images/mobiles/Xiaomi 13T Pro-Alpine Blue.jpg",
      "/images/mobiles/Xiaomi 13T Pro-Meadow Green.jpg",
    ],
    brand: "Xiaomi",
    stock: 80,
    rating: 4.6,
    specs: {
      chipset: "MediaTek Dimensity 9200+",
      ram: "12GB",
      storage: "256GB",
      display: "6.67-inch AMOLED (2712x1220) 144Hz",
      camera: "200MP (Main) + 8MP (Ultra Wide) + 2MP (Macro)",
      battery: "5000mAh (120W HyperCharge)",
      os: "Android 13 (MIUI 14)",
      network: "5G",
    },
    features: ["120W Charging", "Dual Speakers", "Corning Gorilla Glass 5"],
    reviews: [],
  },
  {
    id: 62,
    name: "Redmi Note 12 Pro+",
    category: "mobile",
    price: 399,
    colors: ["Frosted Blue", "Onyx Black", "Polar White", "Stardust Purple"],
    description: "Mid-range phone with 200MP camera and 120Hz AMOLED display.",
    images: [
      "/images/mobiles/Redmi Note 12 Pro+.jpg",
      "/images/mobiles/Redmi Note 12 Pro+-FrostedBlue.jpg",
      "/images/mobiles/Redmi Note 12 Pro+-OnyxBlack.jpg",
      "/images/mobiles/Redmi Note 12 Pro+-PolarWhite.jpg",
      "/images/mobiles/Redmi Note 12 Pro+-Stardust Purple.jpg",
    ],
    brand: "Xiaomi",
    stock: 150,
    rating: 4.5,
    specs: {
      chipset: "MediaTek Dimensity 1080",
      ram: "8GB",
      storage: "256GB",
      display: "6.67-inch AMOLED (2400x1080) 120Hz",
      camera: "200MP (Main) + 8MP (Ultra Wide) + 2MP (Macro)",
      battery: "5000mAh (67W Fast Charging)",
      os: "Android 13 (MIUI 14)",
      network: "5G",
    },
    features: ["3.5mm Jack", "Stereo Speakers", "IR Blaster"],
    reviews: [],
  },
  {
    id: 63,
    name: "POCO F5 Pro",
    category: "mobile",
    price: 549,
    colors: ["Black", "White"],
    description:
      "Gaming-focused phone with Snapdragon 8+ Gen 1 and 144Hz display.",
    images: [
      "/images/mobiles/POCO F5 Pro.webp",
      "/images/mobiles/POCO F5 Pro-Black.jpg",
      "/images/mobiles/POCO F5 Pro-White.jpg",
    ],
    brand: "Xiaomi",
    stock: 70,
    rating: 4.7,
    specs: {
      chipset: "Snapdragon 8+ Gen 1",
      ram: "12GB",
      storage: "256GB",
      display: "6.67-inch AMOLED (2400x1080) 144Hz",
      camera: "64MP (Main) + 8MP (Ultra Wide) + 2MP (Macro)",
      battery: "5160mAh (67W Fast Charging)",
      os: "Android 13 (MIUI 14)",
      network: "5G",
    },
    features: ["LiquidCool Technology", "Dual SIM", "NFC"],
    reviews: [],
  },
  {
    id: 64,
    name: "Xiaomi Mix Fold 3",
    category: "mobile",
    price: 1599,
    colors: ["Emerald Dusk", "Voyager Black"],
    description:
      "Foldable smartphone with Snapdragon 8 Gen 2 and quad-camera system.",
    images: ["/images/mobiles/Xiaomi Mix Fold 3.jpg"],
    brand: "Xiaomi",
    stock: 30,
    rating: 4.9,
    specs: {
      chipset: "Snapdragon 8 Gen 2",
      ram: "16GB",
      storage: "512GB",
      display: "8.03-inch Foldable AMOLED (2160x1914)",
      camera:
        "50MP (Main) + 13MP (Ultra Wide) + 10MP (Telephoto) + 10MP (Periscope)",
      battery: "4500mAh (67W Charging)",
      os: "Android 13 (MIUI Fold)",
      network: "5G",
    },
    features: ["Dolby Vision", "Ceramic Back", "Multi-Axis Hinge"],
    reviews: [],
  },
  {
    id: 65,
    name: "Redmi 12",
    category: "mobile",
    price: 199,
    colors: ["Midnight Black", "Sky Blue", "Polar Silver"],
    description: "Budget phone with 90Hz display and 50MP triple camera.",
    images: [
      "/images/mobiles/Redmi 12.jpg",
      "/images/mobiles/Redmi 12-Polar Silver.jpg",
      "/images/mobiles/Redmi 12-SkyBlue.jpg",
      "/images/mobiles/Redmi 12-Colection.jpg",
    ],
    brand: "Xiaomi",
    stock: 200,
    rating: 4.3,
    specs: {
      chipset: "MediaTek Helio G88",
      ram: "4GB",
      storage: "128GB",
      display: "6.79-inch IPS (2460x1080) 90Hz",
      camera: "50MP (Main) + 8MP (Ultra Wide) + 2MP (Macro)",
      battery: "5000mAh (18W Charging)",
      os: "Android 13 (MIUI 14)",
      network: "4G",
    },
    features: ["Expandable Storage", "3.5mm Jack", "IP53 Splash Resistance"],
    reviews: [],
  },
  {
    id: 66,
    name: "Xiaomi Civi 3",
    category: "mobile",
    price: 499,
    colors: ["Rose Purple", "Adventure Gold", "Mint Green", "Coconut Ash"],
    description:
      "Sleek design with 6.55-inch AMOLED display and dual selfie cameras.",
    images: [
      "/images/mobiles/Xiaomi Civi 3.jpg",
      "/images/mobiles/Xiaomi Civi 3-Adventure Gold.jpg",
      "/images/mobiles/Xiaomi Civi 3-RosePurple.jpg",
      "/images/mobiles/Xiaomi Civi 3-Colection.jpg",
    ],
    brand: "Xiaomi",
    stock: 90,
    rating: 4.6,
    specs: {
      chipset: "MediaTek Dimensity 8200-Ultra",
      ram: "12GB",
      storage: "256GB",
      display: "6.55-inch AMOLED (2400x1080) 120Hz",
      camera: "50MP (Main) + 8MP (Ultra Wide) + 2MP (Macro)",
      battery: "4500mAh (67W Fast Charging)",
      os: "Android 13 (MIUI 14)",
      network: "5G",
    },
    features: [
      "Dual Front Cameras",
      "Ultra-Thin Design",
      "In-Display Fingerprint",
    ],
    reviews: [],
  },
  {
    id: 67,
    name: "Black Shark 6 Pro",
    category: "mobile",
    price: 799,
    colors: ["Black", "Gold"],
    description:
      "Gaming phone with Snapdragon 8 Gen 2 and magnetic pop-up triggers.",
    images: [
      "/images/mobiles/Black Shark 6 Pro.webp",
      "/images/mobiles/Black Shark 6 Pro-Black.jpg",
    ],
    brand: "Xiaomi",
    stock: 40,
    rating: 4.7,
    specs: {
      chipset: "Snapdragon 8 Gen 2",
      ram: "16GB",
      storage: "512GB",
      display: "6.67-inch AMOLED (2400x1080) 144Hz",
      camera: "64MP (Main) + 13MP (Ultra Wide) + 5MP (Macro)",
      battery: "4650mAh (120W Fast Charging)",
      os: "Android 13 (JoyUI 14)",
      network: "5G",
    },
    features: ["Magnetic Triggers", "Liquid Cooling", "RGB Lighting"],
    reviews: [],
  },
  {
    id: 68,
    name: "Xiaomi 13 Lite",
    category: "mobile",
    price: 449,
    colors: ["Lite pink", " Lite blue"],
    description:
      "Lightweight phone with 6.55-inch AMOLED and 32MP selfie camera.",
    images: [
      "/images/mobiles/Xiaomi 13 Lite-LitePink.jpg",
      "/images/mobiles/Xiaomi 13 Lite-LiteBlue.jpg",
    ],
    brand: "Xiaomi",
    stock: 110,
    rating: 4.4,
    specs: {
      chipset: "Snapdragon 7 Gen 1",
      ram: "8GB",
      storage: "128GB",
      display: "6.55-inch AMOLED (2400x1080) 120Hz",
      camera: "64MP (Main) + 8MP (Ultra Wide) + 2MP (Macro)",
      battery: "4300mAh (67W Fast Charging)",
      os: "Android 13 (MIUI 14)",
      network: "5G",
    },
    features: ["32MP Selfie Camera", "Ultra-Slim Bezels", "NFC"],
    reviews: [],
  },
  {
    id: 69,
    name: "Redmi K60 Ultra",
    category: "mobile",
    price: 599,
    colors: ["Black", "White", "Green"],
    description: "Powerful mid-ranger with Dimensity 9200+ and 1.5K display.",
    images: [
      "/images/mobiles/Redmi K60 Ultra.jpg",
      "/images/mobiles/Redmi K60 Ultra-Black.jpg",
      "/images/mobiles/Redmi K60 Ultra-Green.jpg",
      "/images/mobiles/Redmi K60 Ultra-White.jpg",
      "/images/mobiles/Redmi K60 Ultra-Colection.jpg",
    ],
    brand: "Xiaomi",
    stock: 65,
    rating: 4.6,
    specs: {
      chipset: "MediaTek Dimensity 9200+",
      ram: "12GB",
      storage: "256GB",
      display: "6.67-inch AMOLED (2712x1220) 144Hz",
      camera: "50MP (Main) + 8MP (Ultra Wide) + 2MP (Macro)",
      battery: "5500mAh (120W HyperCharge)",
      os: "Android 13 (MIUI 14)",
      network: "5G",
    },
    features: ["144Hz Display", "Dual Stereo Speakers", "X-Axis Motor"],
    reviews: [],
  },
];

export const smartwatch = [
  {
    id: 70,
    name: "Samsung Galaxy Watch 5",
    category: "smart watch",
    price: 299,
    colors: ["black", "ghostwhite", "Silver"],
    description:
      "Advanced smartwatch with BioActive sensor, AMOLED display, and 50-hour battery life.",
    brand: "Samsung",
    images: [
      "/images/smartwatches/Samsung Galaxy Watch 5.jpg",
      "/images/smartwatches/Samsung Galaxy Watch 5-2.jpg",
      "/images/smartwatches/Samsung Galaxy Watch 5-3.jpg",
      "/images/smartwatches/Samsung Galaxy Watch 5-4.jpg",
      "/images/smartwatches/Samsung Galaxy Watch 5-5.jpg",
      "/images/smartwatches/Samsung Galaxy Watch 5-6.jpg",
    ],
    stock: 200,
    rating: 4.7,
    specs: {
      display: "1.4-inch AMOLED (450x450)",
      battery: "410mAh (Up to 50 hours)",
      sensors: ["Heart Rate", "Blood Oxygen", "ECG", "Sleep Tracking"],
      compatibility: "Android & iOS",
      waterproof: "IP68 + 5ATM",
      os: "Wear OS",
    },
    features: ["Wireless Charging", "GPS", "NFC Payments"],
    reviews: [
      {
        user: "Sophia Green",
        rating: 5,
        comment: "Perfect for fitness enthusiasts!",
      },
    ],
  },
  {
    id: 71,
    name: "Apple Watch Series 8",
    category: "smart watch",
    price: 399,
    colors: ["lightblue", "black", "Silver"],
    description:
      "Apple's flagship smartwatch with ECG, temperature sensor, and Crash Detection.",
    brand: "Apple",
    images: [
      "/images/smartwatches/Apple Watch Series 8-2.jpg",
      "/images/smartwatches/Apple Watch Series 8-6.jpg",
      "/images/smartwatches/Apple Watch Series 8-5.jpg",
      "/images/smartwatches/Apple Watch Series 8-4.jpg",
      "/images/smartwatches/Apple Watch Series 8-3.jpg",
      "/images/smartwatches/Apple Watch Series 8.jpg",
    ],
    stock: 180,
    rating: 4.9,
    specs: {
      display: "1.9-inch Retina LTPO (484x396)",
      battery: "308mAh (Up to 18 hours)",
      sensors: ["ECG", "Blood Oxygen", "Temperature"],
      compatibility: "iOS Only",
      waterproof: "IP6X + WR50",
      os: "watchOS 9",
    },
    features: ["Always-On Display", "Fall Detection", "Family Setup"],
    reviews: [
      {
        user: "Laura Black",
        rating: 5,
        comment: "Seamless integration with iPhone.",
      },
    ],
  },
  {
    id: 72,
    name: "Garmin Forerunner 945",
    category: "smart watch",
    price: 599,
    colors: ["Whitestone", "Black"],
    description:
      "Premium GPS smartwatch for athletes with advanced performance metrics and maps.",
    brand: "Garmin",
    images: [
      "/images/smartwatches/Garmin Forerunner 945.jpg",
      "/images/smartwatches/Garmin Forerunner 945-2.jpg",
      "/images/smartwatches/Garmin Forerunner 945-3.jpg",
      "/images/smartwatches/Garmin Forerunner 945-4.jpg",
      "/images/smartwatches/Garmin Forerunner 945-5.jpg",
      "/images/smartwatches/Garmin Forerunner 945-6.jpg",
      "/images/smartwatches/Garmin Forerunner 945-7.jpg",
    ],
    stock: 150,
    rating: 4.8,
    specs: {
      display: "1.2-inch transflective (240x240)",
      battery: "14 days (Smartwatch mode)",
      sensors: ["Heart Rate", "Pulse Ox", "Barometric Altimeter"],
      compatibility: "Android & iOS",
      waterproof: "5ATM",
      os: "Garmin OS",
    },
    features: ["Offline Maps", "Music Storage", "Training Load Focus"],
    reviews: [],
  },
  {
    id: 73,
    name: "Fossil Gen 6",
    category: "smart watch",
    price: 299,
    colors: ["Multicolor", "Black", "Blue", "Brown", "Pink"],
    description:
      "Stylish Wear OS smartwatch with Snapdragon 4100+, SpO2 tracking, and fast charging.",
    brand: "Fossil",
    images: [
      "/images/smartwatches/Fossil Gen 6-3.jpg",
      "/images/smartwatches/Fossil Gen 6.jpg",
      "/images/smartwatches/Fossil Gen 6-2.jpg",
      "/images/smartwatches/Fossil Gen 6-4.jpg",
      "/images/smartwatches/Fossil Gen 6-5.jpg",
    ],
    stock: 120,
    rating: 4.6,
    specs: {
      display: "1.28-inch AMOLED (416x416)",
      battery: "24 hours (Extended mode: 3 days)",
      sensors: ["Heart Rate", "SpO2", "GPS"],
      compatibility: "Android & iOS",
      waterproof: "3ATM",
      os: "Wear OS",
    },
    features: ["Customizable Dials", "Google Assistant", "Quick Charging"],
    reviews: [],
  },
  {
    id: 74,
    name: "Fitbit Sense 2",
    category: "smart watch",
    price: 299,
    colors: [
      "Lunar White/Platinum",
      "Blue Mist/Pale Gold",
      "Shadow Grey/Graphite",
    ],
    description:
      "Health-focused smartwatch with ECG, stress management, and 6+ day battery life.",
    brand: "Fitbit",
    images: [
      "/images/smartwatches/Fitbit Sense 2-6.jpg",
      "/images/smartwatches/Fitbit Sense 2.jpg",
      "/images/smartwatches/Fitbit Sense 2-2.jpg",
      "/images/smartwatches/Fitbit Sense 2-3.jpg",
      "/images/smartwatches/Fitbit Sense 2-4.jpg",
      "/images/smartwatches/Fitbit Sense 2-5.jpg",
      "/images/smartwatches/Fitbit Sense 2-7.jpg",
    ],
    stock: 100,
    rating: 4.7,
    specs: {
      display: "1.58-inch AMOLED (336x336)",
      battery: "6+ days",
      sensors: ["ECG", "EDA Scan", "Skin Temperature"],
      compatibility: "Android & iOS",
      waterproof: "5ATM",
      os: "Fitbit OS",
    },
    features: ["Stress Management", "Sleep Score", "Google Maps/Wallet"],
    reviews: [],
  },
  {
    id: 75,
    name: "Suunto 7",
    category: "smart watch",
    price: 399,
    colors: ["Black", "Black Lime", "Graphite Copper"],
    description:
      "Outdoor smartwatch with 70+ sports modes, offline maps, and Wear OS.",
    brand: "Suunto",
    images: [
      "/images/smartwatches/Suunto 7.jpg",
      "/images/smartwatches/Suunto 7-2.jpg",
      "/images/smartwatches/Suunto 7-3.jpg",
      "/images/smartwatches/Suunto 7-4.jpg",
      "/images/smartwatches/Suunto 7-5.jpg",
      "/images/smartwatches/Suunto 7-6.jpg",
      "/images/smartwatches/Suunto 7-7.jpg",
    ],
    stock: 70,
    rating: 4.8,
    specs: {
      display: "1.39-inch AMOLED (454x454)",
      battery: "2 days (Smartwatch mode)",
      sensors: ["Heart Rate", "Barometer", "GPS"],
      compatibility: "Android & iOS",
      waterproof: "5ATM",
      os: "Wear OS",
    },
    features: ["Offline Maps", "Heatmaps", "FusedTrack"],
    reviews: [],
  },
  {
    id: 76,
    name: "Amazfit GTR 3 Pro",
    category: "smart watch",
    price: 249,
    colors: [
      "Infinite Black",
      "Brown Leather",
      "Graphite Black",
      "Mystic Silver",
    ],
    description:
      "Long-lasting smartwatch with 1.45-inch AMOLED, 12-day battery, and built-in Alexa.",
    brand: "Amazfit",
    images: [
      "/images/smartwatches/Amazfit GTR 3 Pro-4.jpg",
      "/images/smartwatches/Amazfit GTR 3 Pro.jpg",
      "/images/smartwatches/Amazfit GTR 3 Pro-2.jpg",
      "/images/smartwatches/Amazfit GTR 3 Pro-3.jpg",
      "/images/smartwatches/Amazfit GTR 3 Pro-5.jpg",
    ],
    stock: 130,
    rating: 4.7,
    specs: {
      display: "1.45-inch AMOLED (480x480)",
      battery: "12 days (Typical use)",
      sensors: ["Heart Rate", "SpO2", "GPS"],
      compatibility: "Android & iOS",
      waterproof: "5ATM",
      os: "Zepp OS",
    },
    features: ["Alexa Built-in", "150+ Sports Modes", "Bluetooth Calls"],
    reviews: [],
  },
  {
    id: 77,
    name: "TicWatch Pro 3 Ultra",
    category: "smart watch",
    price: 319,
    colors: ["Black", "Brown"],
    description:
      "Dual-layer display smartwatch with Snapdragon 4100, Wear OS, and 72-hour battery.",
    brand: "Mobvoi",
    images: [
      "/images/smartwatches/TicWatch Pro 3 Ultra-5.jpg",
      "/images/smartwatches/TicWatch Pro 3 Ultra.jpg",
      "/images/smartwatches/TicWatch Pro 3 Ultra-2.jpg",
      "/images/smartwatches/TicWatch Pro 3 Ultra-3.jpg",
      "/images/smartwatches/TicWatch Pro 3 Ultra-4.jpg",
    ],
    stock: 85,
    rating: 4.6,
    specs: {
      display: "1.4-inch AMOLED + FSTN (454x454)",
      battery: "72 hours (Smart Mode)",
      sensors: ["Heart Rate", "SpO2", "GPS"],
      compatibility: "Android & iOS",
      waterproof: "IP68",
      os: "Wear OS",
    },
    features: [
      "Dual Display",
      "Essential Mode (45 days)",
      "Military Durability",
    ],
    reviews: [],
  },
  {
    id: 78,
    name: "Huawei Watch GT 3",
    category: "smart watch",
    price: 349,
    colors: ["Huawei Watch GT 3", "Brown leather", "Refillable Cream Kit"],
    description:
      "Fitness smartwatch with 14-day battery, TruSeen 5.0+, and 100+ workout modes.",
    brand: "Huawei",
    images: [
      "/images/smartwatches/Huawei Watch GT 3-4.jpg",
      "/images/smartwatches/Huawei Watch GT 3.jpg",
      "/images/smartwatches/Huawei Watch GT 3-2.jpg",
      "/images/smartwatches/Huawei Watch GT 3-3.jpg",
      "/images/smartwatches/Huawei Watch GT 3-5.jpg",
      "/images/smartwatches/Huawei Watch GT 3-6.jpg",
      "/images/smartwatches/Huawei Watch GT 3-7.jpg",
    ],
    stock: 120,
    rating: 4.9,
    specs: {
      display: "1.43-inch AMOLED (466x466)",
      battery: "14 days (Typical use)",
      sensors: ["Heart Rate", "SpO2", "Temperature"],
      compatibility: "Android & iOS",
      waterproof: "5ATM",
      os: "HarmonyOS",
    },
    features: ["Wireless Charging", "Running Coach", "Music Storage"],
    reviews: [],
  },
  {
    id: 79,
    name: "Withings Steel HR Sport",
    category: "smart watch",
    price: 199,
    colors: ["Black", "White"],
    description:
      "Hybrid smartwatch with analog dial, 25-day battery, and heart rate tracking.",
    brand: "Withings",
    images: [
      "/images/smartwatches/Withings Steel HR Sport-2.jpg",
      "/images/smartwatches/Withings Steel HR Sport.jpg",
      "/images/smartwatches/Withings Steel HR Sport-3.jpg",
      "/images/smartwatches/Withings Steel HR Sport-4.jpg",
      "/images/smartwatches/Withings Steel HR Sport-5.jpg",
    ],
    stock: 110,
    rating: 4.5,
    specs: {
      display: "Analog + OLED sub-dial",
      battery: "25 days",
      sensors: ["Heart Rate", "GPS"],
      compatibility: "Android & iOS",
      waterproof: "5ATM",
      os: "Withings OS",
    },
    features: [
      "Hybrid Design",
      "Automatic Activity Detection",
      "Sleep Tracking",
    ],
    reviews: [],
  },
];

export const accessory = [
  {
    id: 80,
    name: "Anker PowerCore 10000 Portable Charger",
    category: "accessory",
    price: 25,
    colors: ["Black", "White"],
    description:
      "Compact and high-capacity portable charger for phones and tablets.",
    images: [
      "/images/accessories/Anker PowerCore 10000 Portable Charger.jpg",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
    ],
    brand: "Anker",
    stock: 300,
    rating: 4.8,
    reviews: [],
    specs: {
      batteryCapacity: "10000mAh",
      weight: "180g",
      dimensions: "92 × 60 × 22 mm",
      fastCharging: "yes",
      ports: ["USB-A", "Micro-USB"],
      compatibility: ["iPhone", "Android", "Tablets"],
    },
  },
  {
    id: 81,
    name: "Apple AirPods Pro",
    category: "accessory",
    price: 249,
    colors: ["White", "black"],
    description:
      "Premium wireless earbuds with noise cancellation and spatial audio.",
    images: [
      "/images/accessories/Apple AirPods Pro.jpg",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
    ],
    brand: "Apple",
    stock: 150,
    rating: 4.9,
    reviews: [],
    specs: {
      wireless: true,
      noiseCancelling: true,
      batteryLife: "4.5 hours",
      chargingCase: "Yes",
      compatibility: ["iPhone", "Android"],
    },
  },
  {
    id: 82,
    name: "Samsung Galaxy Buds Pro",
    category: "accessory",
    price: 199,
    colors: ["Black", "gray", "white"],
    description:
      "High-quality wireless earbuds with noise cancellation and long battery life.",
    images: [
      "/images/accessories/Samsung Galaxy Buds Pro.jpg",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
    ],
    brand: "Samsung",
    stock: 180,
    rating: 4.7,
    reviews: [],
    specs: {
      wireless: true,
      noiseCancelling: true,
      batteryLife: "5 hours",
      chargingCase: "Yes",
      compatibility: ["iPhone", "Android"],
    },
  },
  {
    id: 83,
    name: "Logitech MX Master 3 Mouse",
    category: "accessory",
    price: 99,
    colors: ["black"],
    description:
      "Wireless ergonomic mouse with advanced precision and long battery life.",
    images: [
      "/images/accessories/Logitech MX Master 3 Mouse.jpg",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
    ],
    brand: "Logitech",
    stock: 250,
    rating: 4.8,
    reviews: [],
    specs: {
      wireless: true,
      dpi: "4000",
      batteryLife: "70 days",
      connectivity: ["USB-C", "Bluetooth"],
    },
  },
  {
    id: 84,
    name: "Fitbit Charge 5 Fitness Tracker",
    category: "accessory",
    price: 149,
    colors: ["Black", "white", "purple", " red"],
    description:
      "Advanced fitness tracker with built-in GPS and heart rate monitoring.",
    images: [
      "/images/accessories/Fitbit Charge 5 Fitness Tracker.jpg",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
    ],
    brand: "Fitbit",
    stock: 130,
    rating: 4.7,
    reviews: [],
    specs: {
      display: "AMOLED",
      batteryLife: "7 days",
      waterResistance: "50m",
      connectivity: ["Bluetooth", "NFC"],
    },
  },
  {
    id: 85,
    name: "RAVPower 60W 6-Port USB Charging Station",
    category: "accessory",
    price: 39,
    colors: ["black"],
    description:
      "Multi-port USB charging station with fast-charging technology.",
    images: [
      "/images/accessories/RAVPower 60W 6-Port USB Charging Station.jpg",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
    ],
    brand: "RAVPower",
    stock: 200,
    rating: 4.6,
    reviews: [],
    specs: {
      ports: 6,
      powerOutput: "60W",
      fastCharging: "yes",
      compatibility: ["Smartphones", "Tablets", "laptops"],
    },
  },
  {
    id: 86,
    name: "Bose QuietComfort 45 Noise Cancelling Headphones",
    category: "accessory",
    price: 329,
    colors: ["Black", "Cream"],
    description:
      "Premium noise-canceling headphones with excellent sound quality.",
    images: [
      "/images/accessories/Bose QuietComfort 45 Noise Cancelling Headphones.jpg",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
    ],
    brand: "Bose",
    stock: 100,
    rating: 4.9,
    reviews: [],
    specs: {
      wireless: true,
      noiseCancelling: true,
      batteryLife: "24 hours",
      connectivity: ["Bluetooth", "AUX"],
    },
  },
  {
    id: 87,
    name: "OtterBox Defender Series Case for iPhone 15",
    category: "accessory",
    price: 49,
    colors: ["Black", "darkgray"],
    description: "Durable and rugged case for iPhone 15 with full protection.",
    images: [
      "/images/accessories/OtterBox Defender Series Case for iPhone 15.jpg",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
    ],
    brand: "OtterBox",
    stock: 250,
    rating: 4.8,
    reviews: [],
    specs: {
      material: "Polycarbonate, Rubber",
      shockproof: true,
      waterResistance: false,
      compatibility: ["iPhone 15"],
    },
  },
  {
    id: 88,
    name: "Sennheiser Momentum 3 Wireless Headphones",
    category: "accessory",
    price: 399,
    colors: ["Black"],
    description:
      "Premium wireless headphones with excellent sound and noise cancellation.",
    images: [
      "/images/accessories/Sennheiser Momentum 3 Wireless Headphones.jpg",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
    ],
    brand: "Sennheiser",
    stock: 90,
    rating: 4.8,
    reviews: [],
    specs: {
      wireless: true,
      noiseCancelling: true,
      batteryLife: "17 hours",
      connectivity: ["Bluetooth", "USB-C"],
    },
  },
  {
    id: 89,
    name: "JBL Flip 5 Portable Bluetooth Speaker",
    category: "accessory",
    price: 119,
    colors: ["Blue", "black"],
    description:
      "Portable Bluetooth speaker with waterproof design and high-quality sound.",
    images: [
      "/images/accessories/JBL Flip 5 Portable Bluetooth Speaker.jpg",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
    ],
    brand: "JBL",
    stock: 180,
    rating: 4.7,
    reviews: [],
    specs: {
      batteryLife: "12 hours",
      waterResistance: "IPX7",
      connectivity: ["Bluetooth"],
    },
  },
  {
    id: 90,
    name: "Razer DeathAdder V2 Gaming Mouse",
    category: "accessory",
    price: 69,
    colors: ["Black"],
    description:
      "Ergonomic gaming mouse with high-precision optical sensor and customizable buttons.",
    images: [
      "/images/accessories/Razer DeathAdder V2 Gaming Mouse.jpg",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
    ],
    brand: "Razer",
    stock: 130,
    rating: 4.8,
    specs: {
      connectivity: "Wired",
      dpi: "20000",
      buttons: "8 programmable",
      rgbLighting: true,
    },
  },
  {
    id: 91,
    name: "Corsair K70 RGB Mechanical Keyboard",
    category: "accessory",
    price: 129,
    colors: ["Black"],
    description:
      "High-performance mechanical keyboard with per-key RGB lighting.",
    images: [
      "/images/accessories/Corsair K70 RGB Mechanical Keyboard.jpg",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
    ],
    brand: "Corsair",
    stock: 100,
    rating: 4.7,
    specs: {
      switchType: "Cherry MX Red",
      connectivity: "Wired",
      backlighting: "RGB Per-Key",
      macroSupport: true,
    },
  },
  {
    id: 92,
    name: "SteelSeries Apex Pro Mechanical Keyboard",
    category: "accessory",
    price: 199,
    colors: ["Black"],
    description: "Adjustable mechanical switches for customizable actuation.",
    images: [
      "/images/accessories/SteelSeries Apex Pro Mechanical Keyboard.jpg",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
    ],
    brand: "SteelSeries",
    stock: 90,
    rating: 4.9,
    specs: {
      switchType: "OmniPoint Adjustable",
      connectivity: "Wired",
      backlighting: "RGB Per-Key",
      macroSupport: true,
    },
  },
  {
    id: 93,
    name: "Logitech G Pro X Wireless Gaming Headset",
    category: "accessory",
    price: 199,
    colors: ["Black"],
    description:
      "Professional-grade wireless gaming headset with Blue VO!CE microphone technology.",
    images: [
      "/images/accessories/Logitech G Pro X Wireless Gaming Headset.png",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
    ],
    brand: "Logitech",
    stock: 80,
    rating: 4.8,
    specs: {
      connectivity: "Wireless 2.4GHz",
      batteryLife: "20 hours",
      surroundSound: "DTS Headphone:X 2.0",
      microphone: "Detachable Blue VO!CE",
    },
  },
  {
    id: 94,
    name: "HyperX Cloud II Gaming Headset",
    category: "accessory",
    price: 99,
    colors: ["darkRed", "Black"],
    description: "Comfortable gaming headset with virtual 7.1 surround sound.",
    images: [
      "/images/accessories/HyperX Cloud II Gaming Headset.jpg",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
    ],
    brand: "HyperX",
    stock: 120,
    rating: 4.7,
    specs: {
      connectivity: "Wired",
      surroundSound: "Virtual 7.1",
      microphone: "Detachable Noise-Canceling",
    },
  },
  {
    id: 95,
    name: "Sony WH-1000XM5 Wireless Noise Cancelling Headphones",
    category: "accessory",
    price: 349,
    colors: ["Silver", "black", "white"],
    description:
      "Industry-leading noise-canceling headphones with up to 30 hours of battery life.",
    images: [
      "/images/accessories/Sony WH-1000XM5 Wireless Noise Cancelling Headphones.jpg",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
      "/images/accessories/",
    ],
    brand: "Sony",
    stock: 70,
    rating: 4.9,
    specs: {
      connectivity: "Bluetooth",
      batteryLife: "30 hours",
      noiseCancelling: true,
      voiceAssistant: "Google Assistant, Alexa",
    },
  },
];

// آرایه‌ای از محصولات که می‌خواهیم در Firestore ذخیره کنیم

// تابعی برای seeding محصولات به Firestore
async function seedProducts() {
  try {
    // برای هر محصول در آرایه، یک سند جدید در کالکشن "products" ایجاد می‌کنیم
    for (const product of laptop) {
      const docRef = await addDoc(collection(db, "products"), product);
      console.log(`محصول "${product.name}" با آیدی ${docRef.id} اضافه شد.`);
    }
    for (const product of mobile) {
      const docRef = await addDoc(collection(db, "products"), product);
      console.log(`محصول "${product.name}" با آیدی ${docRef.id} اضافه شد.`);
    }
    for (const product of smartwatch) {
      const docRef = await addDoc(collection(db, "products"), product);
      console.log(`محصول "${product.name}" با آیدی ${docRef.id} اضافه شد.`);
    }
    for (const product of accessory) {
      const docRef = await addDoc(collection(db, "products"), product);
      console.log(`محصول "${product.name}" با آیدی ${docRef.id} اضافه شد.`);
    }

    console.log("همه محصولات با موفقیت اضافه شدند.");
  } catch (error) {
    console.error("خطا در افزودن محصولات: ", error);
  }
}

// اجرای تابع seeding
seedProducts();
